////////////////////////////////////////////////////////////////////////
//
// gie.h
//
// This file was generated by XMLSpy 2011 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#ifndef _INCLUDED_gie_H_
#define _INCLUDED_gie_H_

#include "xs-types.h"
#include "Node.h"
#include "gie-typeinfo.h"


#if !defined( __GNUC__ )
#ifdef gie_EXPORTS
#define gie_EXPORT	__declspec(dllexport)
#else
#define gie_EXPORT	__declspec(dllimport)
#endif
#else
#define gie_EXPORT
#endif


namespace gie
{

	class TypeBase
	{
	protected:
		xercesc::DOMNode* m_node;
	public:
		TypeBase(xercesc::DOMNode* const& node) : m_node(node) {}
		xercesc::DOMNode* GetNode() const { return m_node; }

		gie_EXPORT xercesc::DOMNode* GetElementNth(const altova::MemberInfo* member, unsigned index);
		gie_EXPORT xercesc::DOMNode* GetElementLast(const altova::MemberInfo* member);
		gie_EXPORT unsigned CountElement(const altova::MemberInfo* member);
		gie_EXPORT void RemoveElement(const altova::MemberInfo* member);
		gie_EXPORT static int GetEnumerationIndex( const string_type sValue, const unsigned enumOffset, const unsigned enumCount);
		gie_EXPORT static string_type GetEnumerationValue( const int index, const unsigned enumOffset, const unsigned enumCount);
	};

	template <typename MemberType, unsigned MemberIndex, unsigned EnumOffset, unsigned EnumCount>
	class MemberAttribute
	{
		TypeBase& m_owner;
	public:
		typedef const MemberType& argument_type;
		typedef MemberType return_type;

		MemberAttribute(TypeBase& owner) : m_owner(owner) {}
		void operator=(argument_type value);
		operator return_type();
		bool exists();
		void remove();
		int GetEnumerationValue();
		void SetEnumerationValue(const int index);
		altova::meta::Attribute info() const { return altova::meta::Attribute(members + MemberIndex); }
	};

	template <typename MemberType>
	class CastAs 
	{
	public:
		static MemberType Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember);
	};

	template <>
	inline bool CastAs<bool>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToBool(node, pMember);
	}

	template <>
	inline double CastAs<double>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToDouble(node, pMember);
	}

	template <>
	inline int CastAs<int>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToInt(node, pMember);
	}

	template <>
	inline unsigned CastAs<unsigned>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToUInt(node, pMember);
	}

	template <>
	inline __int64 CastAs<__int64>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToInt64(node, pMember);
	}

	template <>
	inline unsigned __int64 CastAs<unsigned __int64>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToUInt64(node, pMember);
	}

	template <>
	inline string_type CastAs<string_type>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToString(node, pMember);
	}

	template <>
	inline std::vector<unsigned char> CastAs<std::vector<unsigned char> >::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToBinary(node, pMember);
	}

	template <>
	inline altova::DateTime CastAs<altova::DateTime>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToDateTime(node, pMember);
	}

	template <>
	inline altova::Duration CastAs<altova::Duration>::Do(xercesc::DOMNode* const& node, const altova::MemberInfo* pMember)
	{
		return XercesTreeOperations::CastToDuration(node, pMember);
	}

	template <typename DataType>
	class Iterator : public DataType
	{
		XercesTreeOperations::MemberIterator m_it;
	public:
		Iterator(const XercesTreeOperations::MemberIterator& it) : DataType(0), m_it(it) { if (m_it) this->m_node = *m_it; }
		bool operator++() { if (++m_it) { this->m_node = *m_it; return true; } return false; }
		operator bool() const { return m_it; }		

		DataType& operator*() { return *this; }
		DataType* operator->() { return this; }
	};

	template <typename MemberType, unsigned MemberIndex>
	class MemberElement
	{
		TypeBase& m_owner;
	public:
		MemberElement(TypeBase& owner) : m_owner(owner) {}
		MemberType operator[](unsigned index);
		MemberType first();
		MemberType last();
		MemberType append();
		bool exists();
		unsigned count();
		void remove();
		void remove(unsigned index);
		altova::meta::Element info() const { return altova::meta::Element(members + MemberIndex); }

		Iterator<MemberType> all() { return XercesTreeOperations::GetElements(m_owner.GetNode(), members + MemberIndex); }
	};

	template <typename MemberType, unsigned MemberIndex, unsigned EnumOffset, unsigned EnumCount>
	void MemberAttribute<MemberType, MemberIndex, EnumOffset, EnumCount>::operator=(argument_type value)
	{
		XercesTreeOperations::SetValue(m_owner.GetNode(), members + MemberIndex, value);
	}

	template <typename MemberType, unsigned MemberIndex, unsigned EnumOffset, unsigned EnumCount>
	MemberAttribute<MemberType, MemberIndex, EnumOffset, EnumCount>::operator typename MemberAttribute<MemberType, MemberIndex, EnumOffset, EnumCount>::return_type()
	{
		xercesc::DOMNode* att = XercesTreeOperations::FindAttribute(m_owner.GetNode(), members + MemberIndex);
		if (!XercesTreeOperations::IsValid(att))
			throw altova::InvalidOperationException(_T("Cannot read value of non-existent attribute."));
		return CastAs<MemberType>::Do(att, members + MemberIndex);
	}

	template <typename MemberType, unsigned MemberIndex, unsigned EnumOffset, unsigned EnumCount>
	bool MemberAttribute<MemberType, MemberIndex, EnumOffset, EnumCount>::exists()
	{
		xercesc::DOMNode* att = XercesTreeOperations::FindAttribute(m_owner.GetNode(), members + MemberIndex);
		return XercesTreeOperations::IsValid(att);
	}

	template <typename MemberType, unsigned MemberIndex, unsigned EnumOffset, unsigned EnumCount>
	void MemberAttribute<MemberType, MemberIndex, EnumOffset, EnumCount>::remove()
	{
		XercesTreeOperations::RemoveAttribute(m_owner.GetNode(), members + MemberIndex);
	}
	
	template <typename MemberType, unsigned MemberIndex, unsigned EnumOffset, unsigned EnumCount>
	int MemberAttribute<MemberType, MemberIndex, EnumOffset, EnumCount>::GetEnumerationValue() {
		xercesc::DOMNode* att = XercesTreeOperations::FindAttribute(m_owner.GetNode(), members + MemberIndex);
		if (!XercesTreeOperations::IsValid(att))
			throw altova::InvalidOperationException(_T("Cannot read value of non-existent attribute."));
		string_type sValue = CastAs<string_type>::Do(att, members + MemberIndex);
		return TypeBase::GetEnumerationIndex( sValue, types[members[MemberIndex].DataType].Facets + EnumOffset, EnumCount);
	}

	template <typename MemberType, unsigned MemberIndex, unsigned EnumOffset, unsigned EnumCount>
	void MemberAttribute<MemberType, MemberIndex, EnumOffset, EnumCount>::SetEnumerationValue(const int index) 
	{
		XercesTreeOperations::SetValue(m_owner.GetNode(), members + MemberIndex, TypeBase::GetEnumerationValue(index, types[members[MemberIndex].DataType].Facets + EnumOffset, EnumCount) );
	}

	template <typename MemberType, unsigned MemberIndex>
	MemberType MemberElement<MemberType, MemberIndex>::operator[](unsigned index)
	{
		return m_owner.GetElementNth(members + MemberIndex, index);
	}

	template <typename MemberType, unsigned MemberIndex>
	MemberType MemberElement<MemberType, MemberIndex>::first()
	{
		return m_owner.GetElementNth(members + MemberIndex, 0);
	}

	template <typename MemberType, unsigned MemberIndex>
	MemberType MemberElement<MemberType, MemberIndex>::last()
	{
		return m_owner.GetElementLast(members + MemberIndex);
	}

	template <typename MemberType, unsigned MemberIndex>
	MemberType MemberElement<MemberType, MemberIndex>::append()
	{
		return XercesTreeOperations::AddElement(m_owner.GetNode(), members + MemberIndex);
	}

	template <typename MemberType, unsigned MemberIndex>
	bool MemberElement<MemberType, MemberIndex>::exists()
	{
		return m_owner.GetElementNth(members + MemberIndex, 0) != 0;
	}

	template <typename MemberType, unsigned MemberIndex>
	unsigned MemberElement<MemberType, MemberIndex>::count()
	{
		return m_owner.CountElement(members + MemberIndex);
	}

	template <typename MemberType, unsigned MemberIndex>
	void MemberElement<MemberType, MemberIndex>::remove()
	{
		m_owner.RemoveElement(members + MemberIndex);
	}

	template <typename MemberType, unsigned MemberIndex>
	void MemberElement<MemberType, MemberIndex>::remove(unsigned index)
	{
		XercesTreeOperations::RemoveElement(m_owner.GetNode(), members + MemberIndex, index);
	}

}

namespace gie
{
// Namespace: http://www.isotc211.org/2005/gco 
// SchemaPrefix: gco

namespace gco
{	
class CAbstractObject_Type;
class CAngle_PropertyType;
class CBinary_PropertyType;
class CBinary_Type;
class CBoolean_PropertyType;
class CCharacterString_PropertyType;
class CCodeListValue_Type;
class CDateTime_PropertyType;
class CDate_PropertyType;
class CDate_Type;
class CDecimal_PropertyType;
class CDistance_PropertyType;
class CGenericName_PropertyType;
class CInteger_PropertyType;
class CLength_PropertyType;
class CLocalName_PropertyType;
class CMeasure_PropertyType;
class CMemberName_PropertyType;
class CMemberName_Type;
class CMultiplicityRange_PropertyType;
class CMultiplicityRange_Type;
class CMultiplicity_PropertyType;
class CMultiplicity_Type;
class CNumber_PropertyType;
class CObjectReference_PropertyType;
class CReal_PropertyType;
class CRecordType_PropertyType;
class CRecordType_Type;
class CRecord_PropertyType;
class CScale_PropertyType;
class CScopedName_PropertyType;
class CTypeName_PropertyType;
class CTypeName_Type;
class CUnitOfMeasure_PropertyType;
class CUnlimitedInteger_PropertyType;
class CUnlimitedInteger_Type;
class CUomAngle_PropertyType;
class CUomArea_PropertyType;
class CUomLength_PropertyType;
class CUomScale_PropertyType;
class CUomTime_PropertyType;
class CUomVelocity_PropertyType;
class CUomVolume_PropertyType;
class CDate_TypeType;

} // namespace gco

// Namespace: http://www.isotc211.org/2005/gmd 
// SchemaPrefix: gmd

namespace gmd
{	
class CAbstractDQ_Completeness_Type;
class CAbstractDQ_Element_Type;
class CAbstractDQ_LogicalConsistency_Type;
class CAbstractDQ_PositionalAccuracy_Type;
class CAbstractDQ_Result_Type;
class CAbstractDQ_TemporalAccuracy_Type;
class CAbstractDQ_ThematicAccuracy_Type;
class CAbstractDS_Aggregate_Type;
class CAbstractEX_GeographicExtent_Type;
class CAbstractMD_ContentInformation_Type;
class CAbstractMD_Identification_Type;
class CAbstractMD_SpatialRepresentation_Type;
class CAbstractRS_ReferenceSystem_Type;
class CCI_Address_PropertyType;
class CCI_Address_Type;
class CCI_Citation_PropertyType;
class CCI_Citation_Type;
class CCI_Contact_PropertyType;
class CCI_Contact_Type;
class CCI_DateTypeCode_PropertyType;
class CCI_Date_PropertyType;
class CCI_Date_Type;
class CCI_OnLineFunctionCode_PropertyType;
class CCI_OnlineResource_PropertyType;
class CCI_OnlineResource_Type;
class CCI_PresentationFormCode_PropertyType;
class CCI_ResponsibleParty_PropertyType;
class CCI_ResponsibleParty_Type;
class CCI_RoleCode_PropertyType;
class CCI_Series_PropertyType;
class CCI_Series_Type;
class CCI_Telephone_PropertyType;
class CCI_Telephone_Type;
class CCountry_PropertyType;
class CDQ_AbsoluteExternalPositionalAccuracy_PropertyType;
class CDQ_AbsoluteExternalPositionalAccuracy_Type;
class CDQ_AccuracyOfATimeMeasurement_PropertyType;
class CDQ_AccuracyOfATimeMeasurement_Type;
class CDQ_CompletenessCommission_PropertyType;
class CDQ_CompletenessCommission_Type;
class CDQ_CompletenessOmission_PropertyType;
class CDQ_CompletenessOmission_Type;
class CDQ_Completeness_PropertyType;
class CDQ_ConceptualConsistency_PropertyType;
class CDQ_ConceptualConsistency_Type;
class CDQ_ConformanceResult_PropertyType;
class CDQ_ConformanceResult_Type;
class CDQ_DataQuality_PropertyType;
class CDQ_DataQuality_Type;
class CDQ_DomainConsistency_PropertyType;
class CDQ_DomainConsistency_Type;
class CDQ_Element_PropertyType;
class CDQ_EvaluationMethodTypeCode_PropertyType;
class CDQ_FormatConsistency_PropertyType;
class CDQ_FormatConsistency_Type;
class CDQ_GriddedDataPositionalAccuracy_PropertyType;
class CDQ_GriddedDataPositionalAccuracy_Type;
class CDQ_LogicalConsistency_PropertyType;
class CDQ_NonQuantitativeAttributeAccuracy_PropertyType;
class CDQ_NonQuantitativeAttributeAccuracy_Type;
class CDQ_PositionalAccuracy_PropertyType;
class CDQ_QuantitativeAttributeAccuracy_PropertyType;
class CDQ_QuantitativeAttributeAccuracy_Type;
class CDQ_QuantitativeResult_PropertyType;
class CDQ_QuantitativeResult_Type;
class CDQ_RelativeInternalPositionalAccuracy_PropertyType;
class CDQ_RelativeInternalPositionalAccuracy_Type;
class CDQ_Result_PropertyType;
class CDQ_Scope_PropertyType;
class CDQ_Scope_Type;
class CDQ_TemporalAccuracy_PropertyType;
class CDQ_TemporalConsistency_PropertyType;
class CDQ_TemporalConsistency_Type;
class CDQ_TemporalValidity_PropertyType;
class CDQ_TemporalValidity_Type;
class CDQ_ThematicAccuracy_PropertyType;
class CDQ_ThematicClassificationCorrectness_PropertyType;
class CDQ_ThematicClassificationCorrectness_Type;
class CDQ_TopologicalConsistency_PropertyType;
class CDQ_TopologicalConsistency_Type;
class CDS_Aggregate_PropertyType;
class CDS_AssociationTypeCode_PropertyType;
class CDS_Association_PropertyType;
class CDS_Association_Type;
class CDS_DataSet_PropertyType;
class CDS_DataSet_Type;
class CDS_InitiativeTypeCode_PropertyType;
class CDS_Initiative_PropertyType;
class CDS_Initiative_Type;
class CDS_OtherAggregate_PropertyType;
class CDS_OtherAggregate_Type;
class CDS_Platform_PropertyType;
class CDS_Platform_Type;
class CDS_ProductionSeries_PropertyType;
class CDS_ProductionSeries_Type;
class CDS_Sensor_PropertyType;
class CDS_Sensor_Type;
class CDS_Series_PropertyType;
class CDS_Series_Type;
class CDS_StereoMate_PropertyType;
class CDS_StereoMate_Type;
class CEX_BoundingPolygon_PropertyType;
class CEX_BoundingPolygon_Type;
class CEX_Extent_PropertyType;
class CEX_Extent_Type;
class CEX_GeographicBoundingBox_PropertyType;
class CEX_GeographicBoundingBox_Type;
class CEX_GeographicDescription_PropertyType;
class CEX_GeographicDescription_Type;
class CEX_GeographicExtent_PropertyType;
class CEX_SpatialTemporalExtent_PropertyType;
class CEX_SpatialTemporalExtent_Type;
class CEX_TemporalExtent_PropertyType;
class CEX_TemporalExtent_Type;
class CEX_VerticalExtent_PropertyType;
class CEX_VerticalExtent_Type;
class CLI_Lineage_PropertyType;
class CLI_Lineage_Type;
class CLI_ProcessStep_PropertyType;
class CLI_ProcessStep_Type;
class CLI_Source_PropertyType;
class CLI_Source_Type;
class CLanguageCode_PropertyType;
class CLocalisedCharacterString_PropertyType;
class CLocalisedCharacterString_Type;
class CMD_AggregateInformation_PropertyType;
class CMD_AggregateInformation_Type;
class CMD_ApplicationSchemaInformation_PropertyType;
class CMD_ApplicationSchemaInformation_Type;
class CMD_Band_PropertyType;
class CMD_Band_Type;
class CMD_BrowseGraphic_PropertyType;
class CMD_BrowseGraphic_Type;
class CMD_CellGeometryCode_PropertyType;
class CMD_CharacterSetCode_PropertyType;
class CMD_ClassificationCode_PropertyType;
class CMD_Constraints_PropertyType;
class CMD_Constraints_Type;
class CMD_ContentInformation_PropertyType;
class CMD_CoverageContentTypeCode_PropertyType;
class CMD_CoverageDescription_PropertyType;
class CMD_CoverageDescription_Type;
class CMD_DataIdentification_PropertyType;
class CMD_DataIdentification_Type;
class CMD_DatatypeCode_PropertyType;
class CMD_DigitalTransferOptions_PropertyType;
class CMD_DigitalTransferOptions_Type;
class CMD_DimensionNameTypeCode_PropertyType;
class CMD_Dimension_PropertyType;
class CMD_Dimension_Type;
class CMD_DistributionUnits_PropertyType;
class CMD_Distribution_PropertyType;
class CMD_Distribution_Type;
class CMD_Distributor_PropertyType;
class CMD_Distributor_Type;
class CMD_ExtendedElementInformation_PropertyType;
class CMD_ExtendedElementInformation_Type;
class CMD_FeatureCatalogueDescription_PropertyType;
class CMD_FeatureCatalogueDescription_Type;
class CMD_Format_PropertyType;
class CMD_Format_Type;
class CMD_GeometricObjectTypeCode_PropertyType;
class CMD_GeometricObjects_PropertyType;
class CMD_GeometricObjects_Type;
class CMD_Georectified_PropertyType;
class CMD_Georectified_Type;
class CMD_Georeferenceable_PropertyType;
class CMD_Georeferenceable_Type;
class CMD_GridSpatialRepresentation_PropertyType;
class CMD_GridSpatialRepresentation_Type;
class CMD_Identification_PropertyType;
class CMD_Identifier_PropertyType;
class CMD_Identifier_Type;
class CMD_ImageDescription_PropertyType;
class CMD_ImageDescription_Type;
class CMD_ImagingConditionCode_PropertyType;
class CMD_KeywordTypeCode_PropertyType;
class CMD_Keywords_PropertyType;
class CMD_Keywords_Type;
class CMD_LegalConstraints_PropertyType;
class CMD_LegalConstraints_Type;
class CMD_MaintenanceFrequencyCode_PropertyType;
class CMD_MaintenanceInformation_PropertyType;
class CMD_MaintenanceInformation_Type;
class CMD_MediumFormatCode_PropertyType;
class CMD_MediumNameCode_PropertyType;
class CMD_Medium_PropertyType;
class CMD_Medium_Type;
class CMD_MetadataExtensionInformation_PropertyType;
class CMD_MetadataExtensionInformation_Type;
class CMD_Metadata_PropertyType;
class CMD_Metadata_Type;
class CMD_ObligationCode_PropertyType;
class CMD_ObligationCode_Type;
class CMD_PixelOrientationCode_PropertyType;
class CMD_PixelOrientationCode_Type;
class CMD_PortrayalCatalogueReference_PropertyType;
class CMD_PortrayalCatalogueReference_Type;
class CMD_ProgressCode_PropertyType;
class CMD_RangeDimension_PropertyType;
class CMD_RangeDimension_Type;
class CMD_ReferenceSystem_PropertyType;
class CMD_ReferenceSystem_Type;
class CMD_RepresentativeFraction_PropertyType;
class CMD_RepresentativeFraction_Type;
class CMD_Resolution_PropertyType;
class CMD_Resolution_Type;
class CMD_RestrictionCode_PropertyType;
class CMD_ScopeCode_PropertyType;
class CMD_ScopeDescription_PropertyType;
class CMD_ScopeDescription_Type;
class CMD_SecurityConstraints_PropertyType;
class CMD_SecurityConstraints_Type;
class CMD_ServiceIdentification_PropertyType;
class CMD_ServiceIdentification_Type;
class CMD_SpatialRepresentationTypeCode_PropertyType;
class CMD_SpatialRepresentation_PropertyType;
class CMD_StandardOrderProcess_PropertyType;
class CMD_StandardOrderProcess_Type;
class CMD_TopicCategoryCode_PropertyType;
class CMD_TopicCategoryCode_Type;
class CMD_TopologyLevelCode_PropertyType;
class CMD_Usage_PropertyType;
class CMD_Usage_Type;
class CMD_VectorSpatialRepresentation_PropertyType;
class CMD_VectorSpatialRepresentation_Type;
class CPT_FreeText_PropertyType;
class CPT_FreeText_Type;
class CPT_LocaleContainer_PropertyType;
class CPT_LocaleContainer_Type;
class CPT_Locale_PropertyType;
class CPT_Locale_Type;
class CRS_Identifier_PropertyType;
class CRS_Identifier_Type;
class CRS_ReferenceSystem_PropertyType;
class CURL_PropertyType;
class CMD_ObligationCode_TypeType;
class CMD_PixelOrientationCode_TypeType;
class CMD_TopicCategoryCode_TypeType;

} // namespace gmd

// Namespace: http://www.isotc211.org/2005/gmi 
// SchemaPrefix: gmi

namespace gmi
{	
class CAbstractMI_GeolocationInformation_Type;
class CDirectPosition_PropertyType;
class CLE_Algorithm_PropertyType;
class CLE_Algorithm_Type;
class CLE_NominalResolution_PropertyType;
class CLE_NominalResolution_Type;
class CLE_ProcessStepReport_PropertyType;
class CLE_ProcessStepReport_Type;
class CLE_ProcessStep_PropertyType;
class CLE_ProcessStep_Type;
class CLE_Processing_PropertyType;
class CLE_Processing_Type;
class CLE_Source_PropertyType;
class CLE_Source_Type;
class CMI_AcquisitionInformation_PropertyType;
class CMI_AcquisitionInformation_Type;
class CMI_BandDefinition_PropertyType;
class CMI_Band_PropertyType;
class CMI_Band_Type;
class CMI_ContextCode_PropertyType;
class CMI_CoverageDescription_PropertyType;
class CMI_CoverageDescription_Type;
class CMI_EnvironmentalRecord_PropertyType;
class CMI_EnvironmentalRecord_Type;
class CMI_Event_PropertyType;
class CMI_Event_Type;
class CMI_GCPCollection_PropertyType;
class CMI_GCPCollection_Type;
class CMI_GCP_PropertyType;
class CMI_GCP_Type;
class CMI_GeolocationInformation_PropertyType;
class CMI_GeometryTypeCode_PropertyType;
class CMI_Georectified_PropertyType;
class CMI_Georectified_Type;
class CMI_Georeferenceable_PropertyType;
class CMI_Georeferenceable_Type;
class CMI_ImageDescription_PropertyType;
class CMI_ImageDescription_Type;
class CMI_Instrument_PropertyType;
class CMI_Instrument_Type;
class CMI_Metadata_PropertyType;
class CMI_Metadata_Type;
class CMI_ObjectiveTypeCode_PropertyType;
class CMI_Objective_PropertyType;
class CMI_Objective_Type;
class CMI_OperationTypeCode_PropertyType;
class CMI_Operation_PropertyType;
class CMI_Operation_Type;
class CMI_Plan_PropertyType;
class CMI_Plan_Type;
class CMI_PlatformPass_PropertyType;
class CMI_PlatformPass_Type;
class CMI_Platform_PropertyType;
class CMI_Platform_Type;
class CMI_PolarisationOrientationCode_PropertyType;
class CMI_PriorityCode_PropertyType;
class CMI_RangeElementDescription_PropertyType;
class CMI_RangeElementDescription_Type;
class CMI_RequestedDate_PropertyType;
class CMI_RequestedDate_Type;
class CMI_Requirement_PropertyType;
class CMI_Requirement_Type;
class CMI_SensorTypeCode_PropertyType;
class CMI_SequenceCode_PropertyType;
class CMI_TransferFunctionTypeCode_PropertyType;
class CMI_TriggerCode_PropertyType;
class CMX_DataFile_PropertyType;
class CMX_DataFile_Type;
class CQE_CoverageResult_PropertyType;
class CQE_CoverageResult_Type;
class CQE_Usability_PropertyType;
class CQE_Usability_Type;

} // namespace gmi

// Namespace: http://www.isotc211.org/2005/gsr 
// SchemaPrefix: gsr

namespace gsr
{	
class CSC_CRS_PropertyType;

} // namespace gsr

// Namespace: http://www.isotc211.org/2005/gss 
// SchemaPrefix: gss

namespace gss
{	
class CGM_Object_PropertyType;
class CGM_Point_PropertyType;

} // namespace gss

// Namespace: http://www.isotc211.org/2005/gts 
// SchemaPrefix: gts

namespace gts
{	
class CTM_PeriodDuration_PropertyType;
class CTM_Primitive_PropertyType;

} // namespace gts

// Namespace: http://www.isotc211.org/gcv 
// SchemaPrefix: gcv

namespace gcv
{	
class CCV_CommonPointRule_PropertyType;
class CCV_Coverage_PropertyType;
class CCV_Coverage_Type;
class CCV_DomainObject_PropertyType;
class CCV_DomainObject_Type;
class CCV_InterpolationMethod_PropertyType;
class CCV_SequenceRule_PropertyType;
class CCV_SequenceRule_Type;
class CSD_GCPLocation_PropertyType;
class CSD_GCPLocation_Type;
class CSD_GCPRepository_PropertyType;
class CSD_GCPRepository_Type;
class CSD_ImageIdentifiableGCP_PropertyType;
class CSD_ImageIdentifiableGCP_Type;
class CSD_SensorModel_PropertyType;
class CSD_SensorModel_Type;
class CTM_GeometricPrimitive_PropertyType;
class CTM_GeometricPrimitive_Type;
class CTM_Period_PropertyType;
class CTM_Period_Type;
class CTime_PropertyType;
class CTime_Type;

} // namespace gcv

// Namespace: http://www.lmars.edu.cn/gie 
// SchemaPrefix: gie

namespace gie2
{	
class CAbstractIE_Imagery_Type;
class CAbstractIE_ImageryandGriddedData_Type;
class CAbstractIE_MicrowaveData_Type;
class CCodeListValue_Type;
class CIE_ActiveMWData_Type;
class CIE_CategoricalGriddedData_PropertyType;
class CIE_CategoricalGriddedData_Type;
class CIE_CategoricalValueAndColour_PropertyType;
class CIE_CategoricalValueAndColour_Type;
class CIE_ChannelPropertyCode_PropertyType;
class CIE_ColourPalette_PropertyType;
class CIE_ColourPalette_Type;
class CIE_CompressionSchemaCode_PropertyType;
class CIE_FusedImage_PropertyType;
class CIE_FusedImage_Type;
class CIE_GeolocationSourceCode_PropertyType;
class CIE_GeometricCorrectionModelCode_PropertyType;
class CIE_Georectified_PropertyType;
class CIE_Georectified_Type;
class CIE_Georeferenceable_PropertyType;
class CIE_Georeferenceable_Type;
class CIE_Imagery_PropertyType;
class CIE_ImageryandGriddedData_PropertyType;
class CIE_LayerSequenceCode_PropertyType;
class CIE_LocationGCP_PropertyType;
class CIE_LocationGCP_Type;
class CIE_MosaicElement_PropertyType;
class CIE_MosaicElement_Type;
class CIE_NumericalGriddedData_PropertyType;
class CIE_NumericalGriddedData_Type;
class CIE_OpticalImageTypeCode_PropertyType;
class CIE_OpticalImage_PropertyType;
class CIE_OpticalImage_Type;
class CIE_OpticalSensorTypeCode_PropertyType;
class CIE_OrbitParameter_PropertyType;
class CIE_OrbitParameter_Type;
class CIE_PMWApertureTypeCode_PropertyType;
class CIE_PMWBandNameCode_PropertyType;
class CIE_PMWBand_PropertyType;
class CIE_PMWBand_Type;
class CIE_PMWChannelInfo_PropertyType;
class CIE_PMWChannelInfo_Type;
class CIE_PMWScanningModeCode_PropertyType;
class CIE_PassiveMWData_Type;
class CIE_ProcessingActionCode_PropertyType;
class CIE_RadiometerData_PropertyType;
class CIE_RadiometerData_Type;
class CIE_RadiometricCalibrationTypeCode_PropertyType;
class CIE_SARAmplitudeData_PropertyType;
class CIE_SARAmplitudeData_Type;
class CIE_SARComplexData_PropertyType;
class CIE_SARComplexData_Type;
class CIE_SARComplexLayerTypeCode_PropertyType;
class CIE_SARData_PropertyType;
class CIE_SARData_Type;
class CIE_SARDopplerCentroidParameter_PropertyType;
class CIE_SARDopplerCentroidParameter_Type;
class CIE_SARImagingModeCode_PropertyType;
class CIE_SARSensor_PropertyType;
class CIE_SARSensor_Type;
class CIE_SimulatedImage_PropertyType;
class CIE_SimulatedImage_Type;
class CIE_Storage_PropertyType;
class CIE_Storage_Type;
class CIE_SyntheticImage_PropertyType;
class CIE_SyntheticImage_Type;
class CIE_ThematicGriddedData_PropertyType;
class CIE_ThematicGriddedData_Type;
class Cgie;
class CBooleanType;
class CCategoryType;
class CCountType;
class CQuantityType;
class CSecondDefiningParameterType;
class CisSphereType;
class CisSphereType2;
class CcoordinateOperationAccuracyType;
class CshowType;
class CactuateType;
class CdomainOfValidityType;
class CsecondDefiningParameterType2;

} // namespace gie2

// Namespace: http://www.opengis.net/gml 
// SchemaPrefix: gml

namespace gml
{	
class CAbstractCRSType;
class CAbstractContinuousCoverageType;
class CAbstractCoordinateOperationType;
class CAbstractCoordinateSystemType;
class CAbstractCoverageType;
class CAbstractCurveSegmentType;
class CAbstractCurveType;
class CAbstractDatumType;
class CAbstractDiscreteCoverageType;
class CAbstractFeatureCollectionType;
class CAbstractFeatureMemberType;
class CAbstractFeatureType;
class CAbstractGMLType;
class CAbstractGeneralConversionType;
class CAbstractGeneralDerivedCRSType;
class CAbstractGeneralOperationParameterPropertyType;
class CAbstractGeneralOperationParameterType;
class CAbstractGeneralParameterValuePropertyType;
class CAbstractGeneralParameterValueType;
class CAbstractGeneralTransformationType;
class CAbstractGeometricAggregateType;
class CAbstractGeometricPrimitiveType;
class CAbstractGeometryType;
class CAbstractGriddedSurfaceType;
class CAbstractMemberType;
class CAbstractMetaDataType;
class CAbstractMetadataPropertyType;
class CAbstractParametricCurveSurfaceType;
class CAbstractRingPropertyType;
class CAbstractRingType;
class CAbstractSolidType;
class CAbstractSurfacePatchType;
class CAbstractSurfaceType;
class CAbstractTimeComplexType;
class CAbstractTimeGeometricPrimitiveType;
class CAbstractTimeObjectType;
class CAbstractTimePrimitiveType;
class CAbstractTimeSliceType;
class CAbstractTimeTopologyPrimitiveType;
class CAbstractTopoPrimitiveType;
class CAbstractTopologyType;
class CAffineCSPropertyType;
class CAffineCSType;
class CAffinePlacementType;
class CAggregationType;
class CAngleChoiceType;
class CAngleType;
class CArcByBulgeType;
class CArcByCenterPointType;
class CArcMinutesType;
class CArcSecondsType;
class CArcStringByBulgeType;
class CArcStringType;
class CArcType;
class CAreaType;
class CArrayAssociationType;
class CArrayType;
class CAssociationRoleType;
class CAxisDirection;
class CAxisDirectionList;
class CBSplineType;
class CBagType;
class CBaseUnitType;
class CBezierType;
class CBooleanPropertyType;
class CBoundedFeatureType;
class CBoundingShapeType;
class CCRSPropertyType;
class CCalDate;
class CCartesianCSPropertyType;
class CCartesianCSType;
class CCategoryExtentType;
class CCategoryPropertyType;
class CCircleByCenterPointType;
class CCircleType;
class CClothoidType;
class CCodeListType;
class CCodeOrNilReasonListType;
class CCodeType;
class CCodeWithAuthorityType;
class CCompassPointEnumeration;
class CCompositeCurveType;
class CCompositeSolidType;
class CCompositeSurfaceType;
class CCompositeValueType;
class CCompoundCRSPropertyType;
class CCompoundCRSType;
class CConcatenatedOperationPropertyType;
class CConcatenatedOperationType;
class CConeType;
class CContainerPropertyType;
class CConventionalUnitType;
class CConversionPropertyType;
class CConversionToPreferredUnitType;
class CConversionType;
class CCoordinateOperationPropertyType;
class CCoordinateSystemAxisPropertyType;
class CCoordinateSystemAxisType;
class CCoordinateSystemPropertyType;
class CCoordinatesType;
class CCountExtentType;
class CCountPropertyType;
class CCoverageFunctionType;
class CCubicSplineType;
class CCurveArrayPropertyType;
class CCurveInterpolationType;
class CCurvePropertyType;
class CCurveSegmentArrayPropertyType;
class CCurveType;
class CCylinderType;
class CCylindricalCSPropertyType;
class CCylindricalCSType;
class CDMSAngleType;
class CDataBlockType;
class CDatumPropertyType;
class CDecimalMinutesType;
class CDefinitionBaseType;
class CDefinitionProxyType;
class CDefinitionType;
class CDegreeValueType;
class CDegreesType;
class CDerivationUnitTermType;
class CDerivedCRSPropertyType;
class CDerivedCRSType;
class CDerivedUnitType;
class CDictionaryEntryType;
class CDictionaryType;
class CDirectPositionListType;
class CDirectPositionType;
class CDirectedEdgePropertyType;
class CDirectedFacePropertyType;
class CDirectedNodePropertyType;
class CDirectedObservationAtDistanceType;
class CDirectedObservationType;
class CDirectedTopoSolidPropertyType;
class CDirectionDescriptionType;
class CDirectionPropertyType;
class CDirectionVectorType;
class CDomainSetType;
class CDynamicFeatureCollectionType;
class CDynamicFeatureMemberType;
class CDynamicFeatureType;
class CEdgeType;
class CEllipsoidPropertyType;
class CEllipsoidType;
class CEllipsoidalCSPropertyType;
class CEllipsoidalCSType;
class CEngineeringCRSPropertyType;
class CEngineeringCRSType;
class CEngineeringDatumPropertyType;
class CEngineeringDatumType;
class CEnvelopeType;
class CEnvelopeWithTimePeriodType;
class CFaceType;
class CFeatureArrayPropertyType;
class CFeatureCollectionType;
class CFeaturePropertyType;
class CFileType;
class CFileValueModelType;
class CFormulaType;
class CGeneralConversionPropertyType;
class CGeneralTransformationPropertyType;
class CGenericMetaDataType;
class CGeocentricCRSPropertyType;
class CGeocentricCRSType;
class CGeodesicStringType;
class CGeodesicType;
class CGeodeticCRSPropertyType;
class CGeodeticCRSType;
class CGeodeticDatumPropertyType;
class CGeodeticDatumType;
class CGeographicCRSPropertyType;
class CGeographicCRSType;
class CGeometricComplexPropertyType;
class CGeometricComplexType;
class CGeometricPrimitivePropertyType;
class CGeometryArrayPropertyType;
class CGeometryPropertyType;
class CGridCoverageType;
class CGridDomainType;
class CGridEnvelopeType;
class CGridFunctionType;
class CGridLengthType;
class CGridLimitsType;
class CGridType;
class CHistoryPropertyType;
class CIdentifiedObjectType;
class CImageCRSPropertyType;
class CImageCRSType;
class CImageDatumPropertyType;
class CImageDatumType;
class CIncrementOrder;
class CIndirectEntryType;
class CInlinePropertyType;
class CIsolatedPropertyType;
class CKnotPropertyType;
class CKnotType;
class CKnotTypesType;
class CLengthType;
class CLineStringSegmentArrayPropertyType;
class CLineStringSegmentType;
class CLineStringType;
class CLinearCSPropertyType;
class CLinearCSType;
class CLinearRingPropertyType;
class CLinearRingType;
class CLocationPropertyType;
class CMappingRuleType;
class CMeasureListType;
class CMeasureOrNilReasonListType;
class CMeasureType;
class CMetaDataPropertyType;
class CMovingObjectStatusType;
class CMultiCurveCoverageType;
class CMultiCurveDomainType;
class CMultiCurvePropertyType;
class CMultiCurveType;
class CMultiGeometryPropertyType;
class CMultiGeometryType;
class CMultiPointCoverageType;
class CMultiPointDomainType;
class CMultiPointPropertyType;
class CMultiPointType;
class CMultiSolidCoverageType;
class CMultiSolidDomainType;
class CMultiSolidPropertyType;
class CMultiSolidType;
class CMultiSurfaceCoverageType;
class CMultiSurfaceDomainType;
class CMultiSurfacePropertyType;
class CMultiSurfaceType;
class CNCNameList;
class CNameList;
class CNameOrNilReason;
class CNameOrNilReasonList;
class CNilReasonEnumeration;
class CNilReasonType;
class CNodeType;
class CObliqueCartesianCSPropertyType;
class CObliqueCartesianCSType;
class CObservationType;
class COffsetCurveType;
class COperationMethodPropertyType;
class COperationMethodType;
class COperationParameterGroupPropertyType;
class COperationParameterGroupType;
class COperationParameterPropertyType;
class COperationParameterType;
class COperationPropertyType;
class COrientableCurveType;
class COrientableSurfaceType;
class CParameterValueGroupType;
class CParameterValueType;
class CPassThroughOperationPropertyType;
class CPassThroughOperationType;
class CPointArrayPropertyType;
class CPointPropertyType;
class CPointType;
class CPolarCSPropertyType;
class CPolarCSType;
class CPolygonPatchArrayPropertyType;
class CPolygonPatchType;
class CPolygonType;
class CPolyhedralSurfaceType;
class CPrimeMeridianPropertyType;
class CPrimeMeridianType;
class CPriorityLocationPropertyType;
class CProcedurePropertyType;
class CProjectedCRSPropertyType;
class CProjectedCRSType;
class CQNameList;
class CQuantityExtentType;
class CQuantityPropertyType;
class CRangeParametersType;
class CRangeSetType;
class CRectangleType;
class CRectifiedGridCoverageType;
class CRectifiedGridDomainType;
class CRectifiedGridType;
class CReferenceType;
class CRelatedTimeType;
class CResultType;
class CRingPropertyType;
class CRingType;
class CScaleType;
class CSequenceRuleEnumeration;
class CSequenceRuleType;
class CShellPropertyType;
class CShellType;
class CSignType;
class CSingleCRSPropertyType;
class CSingleOperationPropertyType;
class CSolidArrayPropertyType;
class CSolidPropertyType;
class CSolidType;
class CSpeedType;
class CSphereType;
class CSphericalCSPropertyType;
class CSphericalCSType;
class CStringOrRefType;
class CSuccessionType;
class CSurfaceArrayPropertyType;
class CSurfaceInterpolationType;
class CSurfacePatchArrayPropertyType;
class CSurfacePropertyType;
class CSurfaceType;
class CTargetPropertyType;
class CTemporalCRSPropertyType;
class CTemporalCRSType;
class CTemporalCSPropertyType;
class CTemporalCSType;
class CTemporalDatumBaseType;
class CTemporalDatumPropertyType;
class CTemporalDatumType;
class CTimeCSPropertyType;
class CTimeCSType;
class CTimeCalendarEraPropertyType;
class CTimeCalendarEraType;
class CTimeCalendarPropertyType;
class CTimeCalendarType;
class CTimeClockPropertyType;
class CTimeClockType;
class CTimeCoordinateSystemType;
class CTimeEdgePropertyType;
class CTimeEdgeType;
class CTimeIndeterminateValueType;
class CTimeInstantPropertyType;
class CTimeInstantType;
class CTimeIntervalLengthType;
class CTimeNodePropertyType;
class CTimeNodeType;
class CTimeOrdinalEraPropertyType;
class CTimeOrdinalEraType;
class CTimeOrdinalReferenceSystemType;
class CTimePeriodPropertyType;
class CTimePeriodType;
class CTimePositionType;
class CTimePositionUnion;
class CTimePrimitivePropertyType;
class CTimeReferenceSystemType;
class CTimeTopologyComplexPropertyType;
class CTimeTopologyComplexType;
class CTimeTopologyPrimitivePropertyType;
class CTimeType;
class CTimeUnitType;
class CTinType;
class CTopoComplexMemberType;
class CTopoComplexType;
class CTopoCurvePropertyType;
class CTopoCurveType;
class CTopoPointPropertyType;
class CTopoPointType;
class CTopoPrimitiveArrayAssociationType;
class CTopoPrimitiveMemberType;
class CTopoSolidType;
class CTopoSurfacePropertyType;
class CTopoSurfaceType;
class CTopoVolumePropertyType;
class CTopoVolumeType;
class CTransformationPropertyType;
class CTransformationType;
class CTrianglePatchArrayPropertyType;
class CTriangleType;
class CTriangulatedSurfaceType;
class CUnitDefinitionType;
class CUnitOfMeasureType;
class CUomIdentifier;
class CUomSymbol;
class CUomURI;
class CUserDefinedCSPropertyType;
class CUserDefinedCSType;
class CValueArrayPropertyType;
class CValueArrayType;
class CValuePropertyType;
class CVectorType;
class CVerticalCRSPropertyType;
class CVerticalCRSType;
class CVerticalCSPropertyType;
class CVerticalCSType;
class CVerticalDatumPropertyType;
class CVerticalDatumType;
class CVolumeType;
class CbooleanList;
class CbooleanOrNilReason;
class CbooleanOrNilReasonList;
class CdoubleList;
class CdoubleOrNilReason;
class CdoubleOrNilReasonList;
class CintegerList;
class CintegerOrNilReason;
class CintegerOrNilReasonList;
class CstringOrNilReason;
class CbooleanOrNilReasonListType;
class CCountExtentTypeType;
class CintegerOrNilReasonListType;
class CNilReasonTypeType;
class CDecimalMinutesTypeType;
class CdoubleOrNilReasonListType;
class CintegerListType;
class CArcMinutesTypeType;
class CArcSecondsTypeType;
class CrowsType;
class CRowType;
class CNameOrNilReasonType;
class CNameOrNilReasonType2;
class CNameOrNilReasonListType;
class CrefLocationType;
class CNameListType;
class CintegerOrNilReasonType;
class CintegerOrNilReasonType2;
class CDegreeValueTypeType;
class CdirectionType;
class CdoubleListType;
class CCompassPointEnumerationType;
class CFileValueModelTypeType;
class CNCNameListType;
class CdoubleOrNilReasonType;
class CdoubleOrNilReasonType2;
class CNilReasonEnumerationType;
class CNilReasonEnumerationType2;
class CNilReasonTypeType2;
class CNilReasonTypeType3;
class CrelativePositionType;
class CSequenceRuleEnumerationType;
class CCalDateType;
class CTimePositionUnionType;
class CTimeUnitTypeType;
class CTimeUnitTypeType2;
class CcontrolPointType;
class CbooleanOrNilReasonType;
class CbooleanOrNilReasonType2;
class CstringOrNilReasonType;
class CstringOrNilReasonType2;

} // namespace gml

// Namespace: http://www.w3.org/1999/xlink 
// SchemaPrefix: xlink

namespace xlink
{	

} // namespace xlink

// Namespace: http://www.w3.org/2001/XMLSchema 
// SchemaPrefix: xs

namespace xs
{	
class CENTITIES;
class CENTITY;
class CID;
class CIDREF;
class CIDREFS;
class CNCName;
class CNMTOKEN;
class CNMTOKENS;
class CNOTATION;
class CName;
class CQName;
class CanySimpleType;
class CanyType;
class CanyURI;
class Cbase64Binary;
class Cboolean;
class Cbyte;
class Cdate;
class CdateTime;
class Cdecimal;
class Cdouble;
class Cduration;
class Cfloat;
class CgDay;
class CgMonth;
class CgMonthDay;
class CgYear;
class CgYearMonth;
class ChexBinary;
class Cint;
class Cinteger;
class Clanguage;
class Clong;
class CnegativeInteger;
class CnonNegativeInteger;
class CnonPositiveInteger;
class CnormalizedString;
class CpositiveInteger;
class Cshort;
class Cstring;
class Ctime;
class Ctoken;
class CunsignedByte;
class CunsignedInt;
class CunsignedLong;
class CunsignedShort;
class CbooleanType;
class CstringType;
class CdateTimeType;
class CdecimalType;
class CintegerType;
class CdoubleType;
class CanyURIType;
class CdurationType;
class CpositiveIntegerType;
class CnonNegativeIntegerType;
class CdateType;
class CtimeType;

} // namespace xs


}

// include individual types

// namespace "http://www.isotc211.org/2005/gco"
#include "type_gco.CAbstractObject_Type.h"
#include "type_gco.CAngle_PropertyType.h"
#include "type_gco.CBinary_PropertyType.h"
#include "type_gco.CBinary_Type.h"
#include "type_gco.CBoolean_PropertyType.h"
#include "type_gco.CCharacterString_PropertyType.h"
#include "type_gco.CCodeListValue_Type.h"
#include "type_gco.CDateTime_PropertyType.h"
#include "type_gco.CDate_PropertyType.h"
#include "type_gco.CDate_Type.h"
#include "type_gco.CDecimal_PropertyType.h"
#include "type_gco.CDistance_PropertyType.h"
#include "type_gco.CGenericName_PropertyType.h"
#include "type_gco.CInteger_PropertyType.h"
#include "type_gco.CLength_PropertyType.h"
#include "type_gco.CLocalName_PropertyType.h"
#include "type_gco.CMeasure_PropertyType.h"
#include "type_gco.CMemberName_PropertyType.h"
#include "type_gco.CMemberName_Type.h"
#include "type_gco.CMultiplicityRange_PropertyType.h"
#include "type_gco.CMultiplicityRange_Type.h"
#include "type_gco.CMultiplicity_PropertyType.h"
#include "type_gco.CMultiplicity_Type.h"
#include "type_gco.CNumber_PropertyType.h"
#include "type_gco.CObjectReference_PropertyType.h"
#include "type_gco.CReal_PropertyType.h"
#include "type_gco.CRecordType_PropertyType.h"
#include "type_gco.CRecordType_Type.h"
#include "type_gco.CRecord_PropertyType.h"
#include "type_gco.CScale_PropertyType.h"
#include "type_gco.CScopedName_PropertyType.h"
#include "type_gco.CTypeName_PropertyType.h"
#include "type_gco.CTypeName_Type.h"
#include "type_gco.CUnitOfMeasure_PropertyType.h"
#include "type_gco.CUnlimitedInteger_PropertyType.h"
#include "type_gco.CUnlimitedInteger_Type.h"
#include "type_gco.CUomAngle_PropertyType.h"
#include "type_gco.CUomArea_PropertyType.h"
#include "type_gco.CUomLength_PropertyType.h"
#include "type_gco.CUomScale_PropertyType.h"
#include "type_gco.CUomTime_PropertyType.h"
#include "type_gco.CUomVelocity_PropertyType.h"
#include "type_gco.CUomVolume_PropertyType.h"
#include "type_gco.CDate_TypeType.h"

// namespace "http://www.isotc211.org/2005/gmd"
#include "type_gmd.CAbstractDQ_Completeness_Type.h"
#include "type_gmd.CAbstractDQ_Element_Type.h"
#include "type_gmd.CAbstractDQ_LogicalConsistency_Type.h"
#include "type_gmd.CAbstractDQ_PositionalAccuracy_Type.h"
#include "type_gmd.CAbstractDQ_Result_Type.h"
#include "type_gmd.CAbstractDQ_TemporalAccuracy_Type.h"
#include "type_gmd.CAbstractDQ_ThematicAccuracy_Type.h"
#include "type_gmd.CAbstractDS_Aggregate_Type.h"
#include "type_gmd.CAbstractEX_GeographicExtent_Type.h"
#include "type_gmd.CAbstractMD_ContentInformation_Type.h"
#include "type_gmd.CAbstractMD_Identification_Type.h"
#include "type_gmd.CAbstractMD_SpatialRepresentation_Type.h"
#include "type_gmd.CAbstractRS_ReferenceSystem_Type.h"
#include "type_gmd.CCI_Address_PropertyType.h"
#include "type_gmd.CCI_Address_Type.h"
#include "type_gmd.CCI_Citation_PropertyType.h"
#include "type_gmd.CCI_Citation_Type.h"
#include "type_gmd.CCI_Contact_PropertyType.h"
#include "type_gmd.CCI_Contact_Type.h"
#include "type_gmd.CCI_DateTypeCode_PropertyType.h"
#include "type_gmd.CCI_Date_PropertyType.h"
#include "type_gmd.CCI_Date_Type.h"
#include "type_gmd.CCI_OnLineFunctionCode_PropertyType.h"
#include "type_gmd.CCI_OnlineResource_PropertyType.h"
#include "type_gmd.CCI_OnlineResource_Type.h"
#include "type_gmd.CCI_PresentationFormCode_PropertyType.h"
#include "type_gmd.CCI_ResponsibleParty_PropertyType.h"
#include "type_gmd.CCI_ResponsibleParty_Type.h"
#include "type_gmd.CCI_RoleCode_PropertyType.h"
#include "type_gmd.CCI_Series_PropertyType.h"
#include "type_gmd.CCI_Series_Type.h"
#include "type_gmd.CCI_Telephone_PropertyType.h"
#include "type_gmd.CCI_Telephone_Type.h"
#include "type_gmd.CCountry_PropertyType.h"
#include "type_gmd.CDQ_AbsoluteExternalPositionalAccuracy_PropertyType.h"
#include "type_gmd.CDQ_AbsoluteExternalPositionalAccuracy_Type.h"
#include "type_gmd.CDQ_AccuracyOfATimeMeasurement_PropertyType.h"
#include "type_gmd.CDQ_AccuracyOfATimeMeasurement_Type.h"
#include "type_gmd.CDQ_CompletenessCommission_PropertyType.h"
#include "type_gmd.CDQ_CompletenessCommission_Type.h"
#include "type_gmd.CDQ_CompletenessOmission_PropertyType.h"
#include "type_gmd.CDQ_CompletenessOmission_Type.h"
#include "type_gmd.CDQ_Completeness_PropertyType.h"
#include "type_gmd.CDQ_ConceptualConsistency_PropertyType.h"
#include "type_gmd.CDQ_ConceptualConsistency_Type.h"
#include "type_gmd.CDQ_ConformanceResult_PropertyType.h"
#include "type_gmd.CDQ_ConformanceResult_Type.h"
#include "type_gmd.CDQ_DataQuality_PropertyType.h"
#include "type_gmd.CDQ_DataQuality_Type.h"
#include "type_gmd.CDQ_DomainConsistency_PropertyType.h"
#include "type_gmd.CDQ_DomainConsistency_Type.h"
#include "type_gmd.CDQ_Element_PropertyType.h"
#include "type_gmd.CDQ_EvaluationMethodTypeCode_PropertyType.h"
#include "type_gmd.CDQ_FormatConsistency_PropertyType.h"
#include "type_gmd.CDQ_FormatConsistency_Type.h"
#include "type_gmd.CDQ_GriddedDataPositionalAccuracy_PropertyType.h"
#include "type_gmd.CDQ_GriddedDataPositionalAccuracy_Type.h"
#include "type_gmd.CDQ_LogicalConsistency_PropertyType.h"
#include "type_gmd.CDQ_NonQuantitativeAttributeAccuracy_PropertyType.h"
#include "type_gmd.CDQ_NonQuantitativeAttributeAccuracy_Type.h"
#include "type_gmd.CDQ_PositionalAccuracy_PropertyType.h"
#include "type_gmd.CDQ_QuantitativeAttributeAccuracy_PropertyType.h"
#include "type_gmd.CDQ_QuantitativeAttributeAccuracy_Type.h"
#include "type_gmd.CDQ_QuantitativeResult_PropertyType.h"
#include "type_gmd.CDQ_QuantitativeResult_Type.h"
#include "type_gmd.CDQ_RelativeInternalPositionalAccuracy_PropertyType.h"
#include "type_gmd.CDQ_RelativeInternalPositionalAccuracy_Type.h"
#include "type_gmd.CDQ_Result_PropertyType.h"
#include "type_gmd.CDQ_Scope_PropertyType.h"
#include "type_gmd.CDQ_Scope_Type.h"
#include "type_gmd.CDQ_TemporalAccuracy_PropertyType.h"
#include "type_gmd.CDQ_TemporalConsistency_PropertyType.h"
#include "type_gmd.CDQ_TemporalConsistency_Type.h"
#include "type_gmd.CDQ_TemporalValidity_PropertyType.h"
#include "type_gmd.CDQ_TemporalValidity_Type.h"
#include "type_gmd.CDQ_ThematicAccuracy_PropertyType.h"
#include "type_gmd.CDQ_ThematicClassificationCorrectness_PropertyType.h"
#include "type_gmd.CDQ_ThematicClassificationCorrectness_Type.h"
#include "type_gmd.CDQ_TopologicalConsistency_PropertyType.h"
#include "type_gmd.CDQ_TopologicalConsistency_Type.h"
#include "type_gmd.CDS_Aggregate_PropertyType.h"
#include "type_gmd.CDS_AssociationTypeCode_PropertyType.h"
#include "type_gmd.CDS_Association_PropertyType.h"
#include "type_gmd.CDS_Association_Type.h"
#include "type_gmd.CDS_DataSet_PropertyType.h"
#include "type_gmd.CDS_DataSet_Type.h"
#include "type_gmd.CDS_InitiativeTypeCode_PropertyType.h"
#include "type_gmd.CDS_Initiative_PropertyType.h"
#include "type_gmd.CDS_Initiative_Type.h"
#include "type_gmd.CDS_OtherAggregate_PropertyType.h"
#include "type_gmd.CDS_OtherAggregate_Type.h"
#include "type_gmd.CDS_Platform_PropertyType.h"
#include "type_gmd.CDS_Platform_Type.h"
#include "type_gmd.CDS_ProductionSeries_PropertyType.h"
#include "type_gmd.CDS_ProductionSeries_Type.h"
#include "type_gmd.CDS_Sensor_PropertyType.h"
#include "type_gmd.CDS_Sensor_Type.h"
#include "type_gmd.CDS_Series_PropertyType.h"
#include "type_gmd.CDS_Series_Type.h"
#include "type_gmd.CDS_StereoMate_PropertyType.h"
#include "type_gmd.CDS_StereoMate_Type.h"
#include "type_gmd.CEX_BoundingPolygon_PropertyType.h"
#include "type_gmd.CEX_BoundingPolygon_Type.h"
#include "type_gmd.CEX_Extent_PropertyType.h"
#include "type_gmd.CEX_Extent_Type.h"
#include "type_gmd.CEX_GeographicBoundingBox_PropertyType.h"
#include "type_gmd.CEX_GeographicBoundingBox_Type.h"
#include "type_gmd.CEX_GeographicDescription_PropertyType.h"
#include "type_gmd.CEX_GeographicDescription_Type.h"
#include "type_gmd.CEX_GeographicExtent_PropertyType.h"
#include "type_gmd.CEX_SpatialTemporalExtent_PropertyType.h"
#include "type_gmd.CEX_SpatialTemporalExtent_Type.h"
#include "type_gmd.CEX_TemporalExtent_PropertyType.h"
#include "type_gmd.CEX_TemporalExtent_Type.h"
#include "type_gmd.CEX_VerticalExtent_PropertyType.h"
#include "type_gmd.CEX_VerticalExtent_Type.h"
#include "type_gmd.CLI_Lineage_PropertyType.h"
#include "type_gmd.CLI_Lineage_Type.h"
#include "type_gmd.CLI_ProcessStep_PropertyType.h"
#include "type_gmd.CLI_ProcessStep_Type.h"
#include "type_gmd.CLI_Source_PropertyType.h"
#include "type_gmd.CLI_Source_Type.h"
#include "type_gmd.CLanguageCode_PropertyType.h"
#include "type_gmd.CLocalisedCharacterString_PropertyType.h"
#include "type_gmd.CLocalisedCharacterString_Type.h"
#include "type_gmd.CMD_AggregateInformation_PropertyType.h"
#include "type_gmd.CMD_AggregateInformation_Type.h"
#include "type_gmd.CMD_ApplicationSchemaInformation_PropertyType.h"
#include "type_gmd.CMD_ApplicationSchemaInformation_Type.h"
#include "type_gmd.CMD_Band_PropertyType.h"
#include "type_gmd.CMD_Band_Type.h"
#include "type_gmd.CMD_BrowseGraphic_PropertyType.h"
#include "type_gmd.CMD_BrowseGraphic_Type.h"
#include "type_gmd.CMD_CellGeometryCode_PropertyType.h"
#include "type_gmd.CMD_CharacterSetCode_PropertyType.h"
#include "type_gmd.CMD_ClassificationCode_PropertyType.h"
#include "type_gmd.CMD_Constraints_PropertyType.h"
#include "type_gmd.CMD_Constraints_Type.h"
#include "type_gmd.CMD_ContentInformation_PropertyType.h"
#include "type_gmd.CMD_CoverageContentTypeCode_PropertyType.h"
#include "type_gmd.CMD_CoverageDescription_PropertyType.h"
#include "type_gmd.CMD_CoverageDescription_Type.h"
#include "type_gmd.CMD_DataIdentification_PropertyType.h"
#include "type_gmd.CMD_DataIdentification_Type.h"
#include "type_gmd.CMD_DatatypeCode_PropertyType.h"
#include "type_gmd.CMD_DigitalTransferOptions_PropertyType.h"
#include "type_gmd.CMD_DigitalTransferOptions_Type.h"
#include "type_gmd.CMD_DimensionNameTypeCode_PropertyType.h"
#include "type_gmd.CMD_Dimension_PropertyType.h"
#include "type_gmd.CMD_Dimension_Type.h"
#include "type_gmd.CMD_DistributionUnits_PropertyType.h"
#include "type_gmd.CMD_Distribution_PropertyType.h"
#include "type_gmd.CMD_Distribution_Type.h"
#include "type_gmd.CMD_Distributor_PropertyType.h"
#include "type_gmd.CMD_Distributor_Type.h"
#include "type_gmd.CMD_ExtendedElementInformation_PropertyType.h"
#include "type_gmd.CMD_ExtendedElementInformation_Type.h"
#include "type_gmd.CMD_FeatureCatalogueDescription_PropertyType.h"
#include "type_gmd.CMD_FeatureCatalogueDescription_Type.h"
#include "type_gmd.CMD_Format_PropertyType.h"
#include "type_gmd.CMD_Format_Type.h"
#include "type_gmd.CMD_GeometricObjectTypeCode_PropertyType.h"
#include "type_gmd.CMD_GeometricObjects_PropertyType.h"
#include "type_gmd.CMD_GeometricObjects_Type.h"
#include "type_gmd.CMD_Georectified_PropertyType.h"
#include "type_gmd.CMD_Georectified_Type.h"
#include "type_gmd.CMD_Georeferenceable_PropertyType.h"
#include "type_gmd.CMD_Georeferenceable_Type.h"
#include "type_gmd.CMD_GridSpatialRepresentation_PropertyType.h"
#include "type_gmd.CMD_GridSpatialRepresentation_Type.h"
#include "type_gmd.CMD_Identification_PropertyType.h"
#include "type_gmd.CMD_Identifier_PropertyType.h"
#include "type_gmd.CMD_Identifier_Type.h"
#include "type_gmd.CMD_ImageDescription_PropertyType.h"
#include "type_gmd.CMD_ImageDescription_Type.h"
#include "type_gmd.CMD_ImagingConditionCode_PropertyType.h"
#include "type_gmd.CMD_KeywordTypeCode_PropertyType.h"
#include "type_gmd.CMD_Keywords_PropertyType.h"
#include "type_gmd.CMD_Keywords_Type.h"
#include "type_gmd.CMD_LegalConstraints_PropertyType.h"
#include "type_gmd.CMD_LegalConstraints_Type.h"
#include "type_gmd.CMD_MaintenanceFrequencyCode_PropertyType.h"
#include "type_gmd.CMD_MaintenanceInformation_PropertyType.h"
#include "type_gmd.CMD_MaintenanceInformation_Type.h"
#include "type_gmd.CMD_MediumFormatCode_PropertyType.h"
#include "type_gmd.CMD_MediumNameCode_PropertyType.h"
#include "type_gmd.CMD_Medium_PropertyType.h"
#include "type_gmd.CMD_Medium_Type.h"
#include "type_gmd.CMD_MetadataExtensionInformation_PropertyType.h"
#include "type_gmd.CMD_MetadataExtensionInformation_Type.h"
#include "type_gmd.CMD_Metadata_PropertyType.h"
#include "type_gmd.CMD_Metadata_Type.h"
#include "type_gmd.CMD_ObligationCode_PropertyType.h"
#include "type_gmd.CMD_ObligationCode_Type.h"
#include "type_gmd.CMD_PixelOrientationCode_PropertyType.h"
#include "type_gmd.CMD_PixelOrientationCode_Type.h"
#include "type_gmd.CMD_PortrayalCatalogueReference_PropertyType.h"
#include "type_gmd.CMD_PortrayalCatalogueReference_Type.h"
#include "type_gmd.CMD_ProgressCode_PropertyType.h"
#include "type_gmd.CMD_RangeDimension_PropertyType.h"
#include "type_gmd.CMD_RangeDimension_Type.h"
#include "type_gmd.CMD_ReferenceSystem_PropertyType.h"
#include "type_gmd.CMD_ReferenceSystem_Type.h"
#include "type_gmd.CMD_RepresentativeFraction_PropertyType.h"
#include "type_gmd.CMD_RepresentativeFraction_Type.h"
#include "type_gmd.CMD_Resolution_PropertyType.h"
#include "type_gmd.CMD_Resolution_Type.h"
#include "type_gmd.CMD_RestrictionCode_PropertyType.h"
#include "type_gmd.CMD_ScopeCode_PropertyType.h"
#include "type_gmd.CMD_ScopeDescription_PropertyType.h"
#include "type_gmd.CMD_ScopeDescription_Type.h"
#include "type_gmd.CMD_SecurityConstraints_PropertyType.h"
#include "type_gmd.CMD_SecurityConstraints_Type.h"
#include "type_gmd.CMD_ServiceIdentification_PropertyType.h"
#include "type_gmd.CMD_ServiceIdentification_Type.h"
#include "type_gmd.CMD_SpatialRepresentationTypeCode_PropertyType.h"
#include "type_gmd.CMD_SpatialRepresentation_PropertyType.h"
#include "type_gmd.CMD_StandardOrderProcess_PropertyType.h"
#include "type_gmd.CMD_StandardOrderProcess_Type.h"
#include "type_gmd.CMD_TopicCategoryCode_PropertyType.h"
#include "type_gmd.CMD_TopicCategoryCode_Type.h"
#include "type_gmd.CMD_TopologyLevelCode_PropertyType.h"
#include "type_gmd.CMD_Usage_PropertyType.h"
#include "type_gmd.CMD_Usage_Type.h"
#include "type_gmd.CMD_VectorSpatialRepresentation_PropertyType.h"
#include "type_gmd.CMD_VectorSpatialRepresentation_Type.h"
#include "type_gmd.CPT_FreeText_PropertyType.h"
#include "type_gmd.CPT_FreeText_Type.h"
#include "type_gmd.CPT_LocaleContainer_PropertyType.h"
#include "type_gmd.CPT_LocaleContainer_Type.h"
#include "type_gmd.CPT_Locale_PropertyType.h"
#include "type_gmd.CPT_Locale_Type.h"
#include "type_gmd.CRS_Identifier_PropertyType.h"
#include "type_gmd.CRS_Identifier_Type.h"
#include "type_gmd.CRS_ReferenceSystem_PropertyType.h"
#include "type_gmd.CURL_PropertyType.h"
#include "type_gmd.CMD_ObligationCode_TypeType.h"
#include "type_gmd.CMD_PixelOrientationCode_TypeType.h"
#include "type_gmd.CMD_TopicCategoryCode_TypeType.h"

// namespace "http://www.isotc211.org/2005/gmi"
#include "type_gmi.CAbstractMI_GeolocationInformation_Type.h"
#include "type_gmi.CDirectPosition_PropertyType.h"
#include "type_gmi.CLE_Algorithm_PropertyType.h"
#include "type_gmi.CLE_Algorithm_Type.h"
#include "type_gmi.CLE_NominalResolution_PropertyType.h"
#include "type_gmi.CLE_NominalResolution_Type.h"
#include "type_gmi.CLE_ProcessStepReport_PropertyType.h"
#include "type_gmi.CLE_ProcessStepReport_Type.h"
#include "type_gmi.CLE_ProcessStep_PropertyType.h"
#include "type_gmi.CLE_ProcessStep_Type.h"
#include "type_gmi.CLE_Processing_PropertyType.h"
#include "type_gmi.CLE_Processing_Type.h"
#include "type_gmi.CLE_Source_PropertyType.h"
#include "type_gmi.CLE_Source_Type.h"
#include "type_gmi.CMI_AcquisitionInformation_PropertyType.h"
#include "type_gmi.CMI_AcquisitionInformation_Type.h"
#include "type_gmi.CMI_BandDefinition_PropertyType.h"
#include "type_gmi.CMI_Band_PropertyType.h"
#include "type_gmi.CMI_Band_Type.h"
#include "type_gmi.CMI_ContextCode_PropertyType.h"
#include "type_gmi.CMI_CoverageDescription_PropertyType.h"
#include "type_gmi.CMI_CoverageDescription_Type.h"
#include "type_gmi.CMI_EnvironmentalRecord_PropertyType.h"
#include "type_gmi.CMI_EnvironmentalRecord_Type.h"
#include "type_gmi.CMI_Event_PropertyType.h"
#include "type_gmi.CMI_Event_Type.h"
#include "type_gmi.CMI_GCPCollection_PropertyType.h"
#include "type_gmi.CMI_GCPCollection_Type.h"
#include "type_gmi.CMI_GCP_PropertyType.h"
#include "type_gmi.CMI_GCP_Type.h"
#include "type_gmi.CMI_GeolocationInformation_PropertyType.h"
#include "type_gmi.CMI_GeometryTypeCode_PropertyType.h"
#include "type_gmi.CMI_Georectified_PropertyType.h"
#include "type_gmi.CMI_Georectified_Type.h"
#include "type_gmi.CMI_Georeferenceable_PropertyType.h"
#include "type_gmi.CMI_Georeferenceable_Type.h"
#include "type_gmi.CMI_ImageDescription_PropertyType.h"
#include "type_gmi.CMI_ImageDescription_Type.h"
#include "type_gmi.CMI_Instrument_PropertyType.h"
#include "type_gmi.CMI_Instrument_Type.h"
#include "type_gmi.CMI_Metadata_PropertyType.h"
#include "type_gmi.CMI_Metadata_Type.h"
#include "type_gmi.CMI_ObjectiveTypeCode_PropertyType.h"
#include "type_gmi.CMI_Objective_PropertyType.h"
#include "type_gmi.CMI_Objective_Type.h"
#include "type_gmi.CMI_OperationTypeCode_PropertyType.h"
#include "type_gmi.CMI_Operation_PropertyType.h"
#include "type_gmi.CMI_Operation_Type.h"
#include "type_gmi.CMI_Plan_PropertyType.h"
#include "type_gmi.CMI_Plan_Type.h"
#include "type_gmi.CMI_PlatformPass_PropertyType.h"
#include "type_gmi.CMI_PlatformPass_Type.h"
#include "type_gmi.CMI_Platform_PropertyType.h"
#include "type_gmi.CMI_Platform_Type.h"
#include "type_gmi.CMI_PolarisationOrientationCode_PropertyType.h"
#include "type_gmi.CMI_PriorityCode_PropertyType.h"
#include "type_gmi.CMI_RangeElementDescription_PropertyType.h"
#include "type_gmi.CMI_RangeElementDescription_Type.h"
#include "type_gmi.CMI_RequestedDate_PropertyType.h"
#include "type_gmi.CMI_RequestedDate_Type.h"
#include "type_gmi.CMI_Requirement_PropertyType.h"
#include "type_gmi.CMI_Requirement_Type.h"
#include "type_gmi.CMI_SensorTypeCode_PropertyType.h"
#include "type_gmi.CMI_SequenceCode_PropertyType.h"
#include "type_gmi.CMI_TransferFunctionTypeCode_PropertyType.h"
#include "type_gmi.CMI_TriggerCode_PropertyType.h"
#include "type_gmi.CMX_DataFile_PropertyType.h"
#include "type_gmi.CMX_DataFile_Type.h"
#include "type_gmi.CQE_CoverageResult_PropertyType.h"
#include "type_gmi.CQE_CoverageResult_Type.h"
#include "type_gmi.CQE_Usability_PropertyType.h"
#include "type_gmi.CQE_Usability_Type.h"

// namespace "http://www.isotc211.org/2005/gsr"
#include "type_gsr.CSC_CRS_PropertyType.h"

// namespace "http://www.isotc211.org/2005/gss"
#include "type_gss.CGM_Object_PropertyType.h"
#include "type_gss.CGM_Point_PropertyType.h"

// namespace "http://www.isotc211.org/2005/gts"
#include "type_gts.CTM_PeriodDuration_PropertyType.h"
#include "type_gts.CTM_Primitive_PropertyType.h"

// namespace "http://www.isotc211.org/gcv"
#include "type_gcv.CCV_CommonPointRule_PropertyType.h"
#include "type_gcv.CCV_Coverage_PropertyType.h"
#include "type_gcv.CCV_Coverage_Type.h"
#include "type_gcv.CCV_DomainObject_PropertyType.h"
#include "type_gcv.CCV_DomainObject_Type.h"
#include "type_gcv.CCV_InterpolationMethod_PropertyType.h"
#include "type_gcv.CCV_SequenceRule_PropertyType.h"
#include "type_gcv.CCV_SequenceRule_Type.h"
#include "type_gcv.CSD_GCPLocation_PropertyType.h"
#include "type_gcv.CSD_GCPLocation_Type.h"
#include "type_gcv.CSD_GCPRepository_PropertyType.h"
#include "type_gcv.CSD_GCPRepository_Type.h"
#include "type_gcv.CSD_ImageIdentifiableGCP_PropertyType.h"
#include "type_gcv.CSD_ImageIdentifiableGCP_Type.h"
#include "type_gcv.CSD_SensorModel_PropertyType.h"
#include "type_gcv.CSD_SensorModel_Type.h"
#include "type_gcv.CTM_GeometricPrimitive_PropertyType.h"
#include "type_gcv.CTM_GeometricPrimitive_Type.h"
#include "type_gcv.CTM_Period_PropertyType.h"
#include "type_gcv.CTM_Period_Type.h"
#include "type_gcv.CTime_PropertyType.h"
#include "type_gcv.CTime_Type.h"

// namespace "http://www.lmars.edu.cn/gie"
#include "type_gie2.CAbstractIE_Imagery_Type.h"
#include "type_gie2.CAbstractIE_ImageryandGriddedData_Type.h"
#include "type_gie2.CAbstractIE_MicrowaveData_Type.h"
#include "type_gie2.CCodeListValue_Type.h"
#include "type_gie2.CIE_ActiveMWData_Type.h"
#include "type_gie2.CIE_CategoricalGriddedData_PropertyType.h"
#include "type_gie2.CIE_CategoricalGriddedData_Type.h"
#include "type_gie2.CIE_CategoricalValueAndColour_PropertyType.h"
#include "type_gie2.CIE_CategoricalValueAndColour_Type.h"
#include "type_gie2.CIE_ChannelPropertyCode_PropertyType.h"
#include "type_gie2.CIE_ColourPalette_PropertyType.h"
#include "type_gie2.CIE_ColourPalette_Type.h"
#include "type_gie2.CIE_CompressionSchemaCode_PropertyType.h"
#include "type_gie2.CIE_FusedImage_PropertyType.h"
#include "type_gie2.CIE_FusedImage_Type.h"
#include "type_gie2.CIE_GeolocationSourceCode_PropertyType.h"
#include "type_gie2.CIE_GeometricCorrectionModelCode_PropertyType.h"
#include "type_gie2.CIE_Georectified_PropertyType.h"
#include "type_gie2.CIE_Georectified_Type.h"
#include "type_gie2.CIE_Georeferenceable_PropertyType.h"
#include "type_gie2.CIE_Georeferenceable_Type.h"
#include "type_gie2.CIE_Imagery_PropertyType.h"
#include "type_gie2.CIE_ImageryandGriddedData_PropertyType.h"
#include "type_gie2.CIE_LayerSequenceCode_PropertyType.h"
#include "type_gie2.CIE_LocationGCP_PropertyType.h"
#include "type_gie2.CIE_LocationGCP_Type.h"
#include "type_gie2.CIE_MosaicElement_PropertyType.h"
#include "type_gie2.CIE_MosaicElement_Type.h"
#include "type_gie2.CIE_NumericalGriddedData_PropertyType.h"
#include "type_gie2.CIE_NumericalGriddedData_Type.h"
#include "type_gie2.CIE_OpticalImageTypeCode_PropertyType.h"
#include "type_gie2.CIE_OpticalImage_PropertyType.h"
#include "type_gie2.CIE_OpticalImage_Type.h"
#include "type_gie2.CIE_OpticalSensorTypeCode_PropertyType.h"
#include "type_gie2.CIE_OrbitParameter_PropertyType.h"
#include "type_gie2.CIE_OrbitParameter_Type.h"
#include "type_gie2.CIE_PMWApertureTypeCode_PropertyType.h"
#include "type_gie2.CIE_PMWBandNameCode_PropertyType.h"
#include "type_gie2.CIE_PMWBand_PropertyType.h"
#include "type_gie2.CIE_PMWBand_Type.h"
#include "type_gie2.CIE_PMWChannelInfo_PropertyType.h"
#include "type_gie2.CIE_PMWChannelInfo_Type.h"
#include "type_gie2.CIE_PMWScanningModeCode_PropertyType.h"
#include "type_gie2.CIE_PassiveMWData_Type.h"
#include "type_gie2.CIE_ProcessingActionCode_PropertyType.h"
#include "type_gie2.CIE_RadiometerData_PropertyType.h"
#include "type_gie2.CIE_RadiometerData_Type.h"
#include "type_gie2.CIE_RadiometricCalibrationTypeCode_PropertyType.h"
#include "type_gie2.CIE_SARAmplitudeData_PropertyType.h"
#include "type_gie2.CIE_SARAmplitudeData_Type.h"
#include "type_gie2.CIE_SARComplexData_PropertyType.h"
#include "type_gie2.CIE_SARComplexData_Type.h"
#include "type_gie2.CIE_SARComplexLayerTypeCode_PropertyType.h"
#include "type_gie2.CIE_SARData_PropertyType.h"
#include "type_gie2.CIE_SARData_Type.h"
#include "type_gie2.CIE_SARDopplerCentroidParameter_PropertyType.h"
#include "type_gie2.CIE_SARDopplerCentroidParameter_Type.h"
#include "type_gie2.CIE_SARImagingModeCode_PropertyType.h"
#include "type_gie2.CIE_SARSensor_PropertyType.h"
#include "type_gie2.CIE_SARSensor_Type.h"
#include "type_gie2.CIE_SimulatedImage_PropertyType.h"
#include "type_gie2.CIE_SimulatedImage_Type.h"
#include "type_gie2.CIE_Storage_PropertyType.h"
#include "type_gie2.CIE_Storage_Type.h"
#include "type_gie2.CIE_SyntheticImage_PropertyType.h"
#include "type_gie2.CIE_SyntheticImage_Type.h"
#include "type_gie2.CIE_ThematicGriddedData_PropertyType.h"
#include "type_gie2.CIE_ThematicGriddedData_Type.h"
#include "type_gie2.Cgie.h"
#include "type_gie2.CBooleanType.h"
#include "type_gie2.CCategoryType.h"
#include "type_gie2.CCountType.h"
#include "type_gie2.CQuantityType.h"
#include "type_gie2.CSecondDefiningParameterType.h"
#include "type_gie2.CisSphereType.h"
#include "type_gie2.CisSphereType2.h"
#include "type_gie2.CcoordinateOperationAccuracyType.h"
#include "type_gie2.CshowType.h"
#include "type_gie2.CactuateType.h"
#include "type_gie2.CdomainOfValidityType.h"
#include "type_gie2.CsecondDefiningParameterType2.h"

// namespace "http://www.opengis.net/gml"
#include "type_gml.CAbstractCRSType.h"
#include "type_gml.CAbstractContinuousCoverageType.h"
#include "type_gml.CAbstractCoordinateOperationType.h"
#include "type_gml.CAbstractCoordinateSystemType.h"
#include "type_gml.CAbstractCoverageType.h"
#include "type_gml.CAbstractCurveSegmentType.h"
#include "type_gml.CAbstractCurveType.h"
#include "type_gml.CAbstractDatumType.h"
#include "type_gml.CAbstractDiscreteCoverageType.h"
#include "type_gml.CAbstractFeatureCollectionType.h"
#include "type_gml.CAbstractFeatureMemberType.h"
#include "type_gml.CAbstractFeatureType.h"
#include "type_gml.CAbstractGMLType.h"
#include "type_gml.CAbstractGeneralConversionType.h"
#include "type_gml.CAbstractGeneralDerivedCRSType.h"
#include "type_gml.CAbstractGeneralOperationParameterPropertyType.h"
#include "type_gml.CAbstractGeneralOperationParameterType.h"
#include "type_gml.CAbstractGeneralParameterValuePropertyType.h"
#include "type_gml.CAbstractGeneralParameterValueType.h"
#include "type_gml.CAbstractGeneralTransformationType.h"
#include "type_gml.CAbstractGeometricAggregateType.h"
#include "type_gml.CAbstractGeometricPrimitiveType.h"
#include "type_gml.CAbstractGeometryType.h"
#include "type_gml.CAbstractGriddedSurfaceType.h"
#include "type_gml.CAbstractMemberType.h"
#include "type_gml.CAbstractMetaDataType.h"
#include "type_gml.CAbstractMetadataPropertyType.h"
#include "type_gml.CAbstractParametricCurveSurfaceType.h"
#include "type_gml.CAbstractRingPropertyType.h"
#include "type_gml.CAbstractRingType.h"
#include "type_gml.CAbstractSolidType.h"
#include "type_gml.CAbstractSurfacePatchType.h"
#include "type_gml.CAbstractSurfaceType.h"
#include "type_gml.CAbstractTimeComplexType.h"
#include "type_gml.CAbstractTimeGeometricPrimitiveType.h"
#include "type_gml.CAbstractTimeObjectType.h"
#include "type_gml.CAbstractTimePrimitiveType.h"
#include "type_gml.CAbstractTimeSliceType.h"
#include "type_gml.CAbstractTimeTopologyPrimitiveType.h"
#include "type_gml.CAbstractTopoPrimitiveType.h"
#include "type_gml.CAbstractTopologyType.h"
#include "type_gml.CAffineCSPropertyType.h"
#include "type_gml.CAffineCSType.h"
#include "type_gml.CAffinePlacementType.h"
#include "type_gml.CAggregationType.h"
#include "type_gml.CAngleChoiceType.h"
#include "type_gml.CAngleType.h"
#include "type_gml.CArcByBulgeType.h"
#include "type_gml.CArcByCenterPointType.h"
#include "type_gml.CArcMinutesType.h"
#include "type_gml.CArcSecondsType.h"
#include "type_gml.CArcStringByBulgeType.h"
#include "type_gml.CArcStringType.h"
#include "type_gml.CArcType.h"
#include "type_gml.CAreaType.h"
#include "type_gml.CArrayAssociationType.h"
#include "type_gml.CArrayType.h"
#include "type_gml.CAssociationRoleType.h"
#include "type_gml.CAxisDirection.h"
#include "type_gml.CAxisDirectionList.h"
#include "type_gml.CBSplineType.h"
#include "type_gml.CBagType.h"
#include "type_gml.CBaseUnitType.h"
#include "type_gml.CBezierType.h"
#include "type_gml.CBooleanPropertyType.h"
#include "type_gml.CBoundedFeatureType.h"
#include "type_gml.CBoundingShapeType.h"
#include "type_gml.CCRSPropertyType.h"
#include "type_gml.CCalDate.h"
#include "type_gml.CCartesianCSPropertyType.h"
#include "type_gml.CCartesianCSType.h"
#include "type_gml.CCategoryExtentType.h"
#include "type_gml.CCategoryPropertyType.h"
#include "type_gml.CCircleByCenterPointType.h"
#include "type_gml.CCircleType.h"
#include "type_gml.CClothoidType.h"
#include "type_gml.CCodeListType.h"
#include "type_gml.CCodeOrNilReasonListType.h"
#include "type_gml.CCodeType.h"
#include "type_gml.CCodeWithAuthorityType.h"
#include "type_gml.CCompassPointEnumeration.h"
#include "type_gml.CCompositeCurveType.h"
#include "type_gml.CCompositeSolidType.h"
#include "type_gml.CCompositeSurfaceType.h"
#include "type_gml.CCompositeValueType.h"
#include "type_gml.CCompoundCRSPropertyType.h"
#include "type_gml.CCompoundCRSType.h"
#include "type_gml.CConcatenatedOperationPropertyType.h"
#include "type_gml.CConcatenatedOperationType.h"
#include "type_gml.CConeType.h"
#include "type_gml.CContainerPropertyType.h"
#include "type_gml.CConventionalUnitType.h"
#include "type_gml.CConversionPropertyType.h"
#include "type_gml.CConversionToPreferredUnitType.h"
#include "type_gml.CConversionType.h"
#include "type_gml.CCoordinateOperationPropertyType.h"
#include "type_gml.CCoordinateSystemAxisPropertyType.h"
#include "type_gml.CCoordinateSystemAxisType.h"
#include "type_gml.CCoordinateSystemPropertyType.h"
#include "type_gml.CCoordinatesType.h"
#include "type_gml.CCountExtentType.h"
#include "type_gml.CCountPropertyType.h"
#include "type_gml.CCoverageFunctionType.h"
#include "type_gml.CCubicSplineType.h"
#include "type_gml.CCurveArrayPropertyType.h"
#include "type_gml.CCurveInterpolationType.h"
#include "type_gml.CCurvePropertyType.h"
#include "type_gml.CCurveSegmentArrayPropertyType.h"
#include "type_gml.CCurveType.h"
#include "type_gml.CCylinderType.h"
#include "type_gml.CCylindricalCSPropertyType.h"
#include "type_gml.CCylindricalCSType.h"
#include "type_gml.CDMSAngleType.h"
#include "type_gml.CDataBlockType.h"
#include "type_gml.CDatumPropertyType.h"
#include "type_gml.CDecimalMinutesType.h"
#include "type_gml.CDefinitionBaseType.h"
#include "type_gml.CDefinitionProxyType.h"
#include "type_gml.CDefinitionType.h"
#include "type_gml.CDegreeValueType.h"
#include "type_gml.CDegreesType.h"
#include "type_gml.CDerivationUnitTermType.h"
#include "type_gml.CDerivedCRSPropertyType.h"
#include "type_gml.CDerivedCRSType.h"
#include "type_gml.CDerivedUnitType.h"
#include "type_gml.CDictionaryEntryType.h"
#include "type_gml.CDictionaryType.h"
#include "type_gml.CDirectPositionListType.h"
#include "type_gml.CDirectPositionType.h"
#include "type_gml.CDirectedEdgePropertyType.h"
#include "type_gml.CDirectedFacePropertyType.h"
#include "type_gml.CDirectedNodePropertyType.h"
#include "type_gml.CDirectedObservationAtDistanceType.h"
#include "type_gml.CDirectedObservationType.h"
#include "type_gml.CDirectedTopoSolidPropertyType.h"
#include "type_gml.CDirectionDescriptionType.h"
#include "type_gml.CDirectionPropertyType.h"
#include "type_gml.CDirectionVectorType.h"
#include "type_gml.CDomainSetType.h"
#include "type_gml.CDynamicFeatureCollectionType.h"
#include "type_gml.CDynamicFeatureMemberType.h"
#include "type_gml.CDynamicFeatureType.h"
#include "type_gml.CEdgeType.h"
#include "type_gml.CEllipsoidPropertyType.h"
#include "type_gml.CEllipsoidType.h"
#include "type_gml.CEllipsoidalCSPropertyType.h"
#include "type_gml.CEllipsoidalCSType.h"
#include "type_gml.CEngineeringCRSPropertyType.h"
#include "type_gml.CEngineeringCRSType.h"
#include "type_gml.CEngineeringDatumPropertyType.h"
#include "type_gml.CEngineeringDatumType.h"
#include "type_gml.CEnvelopeType.h"
#include "type_gml.CEnvelopeWithTimePeriodType.h"
#include "type_gml.CFaceType.h"
#include "type_gml.CFeatureArrayPropertyType.h"
#include "type_gml.CFeatureCollectionType.h"
#include "type_gml.CFeaturePropertyType.h"
#include "type_gml.CFileType.h"
#include "type_gml.CFileValueModelType.h"
#include "type_gml.CFormulaType.h"
#include "type_gml.CGeneralConversionPropertyType.h"
#include "type_gml.CGeneralTransformationPropertyType.h"
#include "type_gml.CGenericMetaDataType.h"
#include "type_gml.CGeocentricCRSPropertyType.h"
#include "type_gml.CGeocentricCRSType.h"
#include "type_gml.CGeodesicStringType.h"
#include "type_gml.CGeodesicType.h"
#include "type_gml.CGeodeticCRSPropertyType.h"
#include "type_gml.CGeodeticCRSType.h"
#include "type_gml.CGeodeticDatumPropertyType.h"
#include "type_gml.CGeodeticDatumType.h"
#include "type_gml.CGeographicCRSPropertyType.h"
#include "type_gml.CGeographicCRSType.h"
#include "type_gml.CGeometricComplexPropertyType.h"
#include "type_gml.CGeometricComplexType.h"
#include "type_gml.CGeometricPrimitivePropertyType.h"
#include "type_gml.CGeometryArrayPropertyType.h"
#include "type_gml.CGeometryPropertyType.h"
#include "type_gml.CGridCoverageType.h"
#include "type_gml.CGridDomainType.h"
#include "type_gml.CGridEnvelopeType.h"
#include "type_gml.CGridFunctionType.h"
#include "type_gml.CGridLengthType.h"
#include "type_gml.CGridLimitsType.h"
#include "type_gml.CGridType.h"
#include "type_gml.CHistoryPropertyType.h"
#include "type_gml.CIdentifiedObjectType.h"
#include "type_gml.CImageCRSPropertyType.h"
#include "type_gml.CImageCRSType.h"
#include "type_gml.CImageDatumPropertyType.h"
#include "type_gml.CImageDatumType.h"
#include "type_gml.CIncrementOrder.h"
#include "type_gml.CIndirectEntryType.h"
#include "type_gml.CInlinePropertyType.h"
#include "type_gml.CIsolatedPropertyType.h"
#include "type_gml.CKnotPropertyType.h"
#include "type_gml.CKnotType.h"
#include "type_gml.CKnotTypesType.h"
#include "type_gml.CLengthType.h"
#include "type_gml.CLineStringSegmentArrayPropertyType.h"
#include "type_gml.CLineStringSegmentType.h"
#include "type_gml.CLineStringType.h"
#include "type_gml.CLinearCSPropertyType.h"
#include "type_gml.CLinearCSType.h"
#include "type_gml.CLinearRingPropertyType.h"
#include "type_gml.CLinearRingType.h"
#include "type_gml.CLocationPropertyType.h"
#include "type_gml.CMappingRuleType.h"
#include "type_gml.CMeasureListType.h"
#include "type_gml.CMeasureOrNilReasonListType.h"
#include "type_gml.CMeasureType.h"
#include "type_gml.CMetaDataPropertyType.h"
#include "type_gml.CMovingObjectStatusType.h"
#include "type_gml.CMultiCurveCoverageType.h"
#include "type_gml.CMultiCurveDomainType.h"
#include "type_gml.CMultiCurvePropertyType.h"
#include "type_gml.CMultiCurveType.h"
#include "type_gml.CMultiGeometryPropertyType.h"
#include "type_gml.CMultiGeometryType.h"
#include "type_gml.CMultiPointCoverageType.h"
#include "type_gml.CMultiPointDomainType.h"
#include "type_gml.CMultiPointPropertyType.h"
#include "type_gml.CMultiPointType.h"
#include "type_gml.CMultiSolidCoverageType.h"
#include "type_gml.CMultiSolidDomainType.h"
#include "type_gml.CMultiSolidPropertyType.h"
#include "type_gml.CMultiSolidType.h"
#include "type_gml.CMultiSurfaceCoverageType.h"
#include "type_gml.CMultiSurfaceDomainType.h"
#include "type_gml.CMultiSurfacePropertyType.h"
#include "type_gml.CMultiSurfaceType.h"
#include "type_gml.CNCNameList.h"
#include "type_gml.CNameList.h"
#include "type_gml.CNameOrNilReason.h"
#include "type_gml.CNameOrNilReasonList.h"
#include "type_gml.CNilReasonEnumeration.h"
#include "type_gml.CNilReasonType.h"
#include "type_gml.CNodeType.h"
#include "type_gml.CObliqueCartesianCSPropertyType.h"
#include "type_gml.CObliqueCartesianCSType.h"
#include "type_gml.CObservationType.h"
#include "type_gml.COffsetCurveType.h"
#include "type_gml.COperationMethodPropertyType.h"
#include "type_gml.COperationMethodType.h"
#include "type_gml.COperationParameterGroupPropertyType.h"
#include "type_gml.COperationParameterGroupType.h"
#include "type_gml.COperationParameterPropertyType.h"
#include "type_gml.COperationParameterType.h"
#include "type_gml.COperationPropertyType.h"
#include "type_gml.COrientableCurveType.h"
#include "type_gml.COrientableSurfaceType.h"
#include "type_gml.CParameterValueGroupType.h"
#include "type_gml.CParameterValueType.h"
#include "type_gml.CPassThroughOperationPropertyType.h"
#include "type_gml.CPassThroughOperationType.h"
#include "type_gml.CPointArrayPropertyType.h"
#include "type_gml.CPointPropertyType.h"
#include "type_gml.CPointType.h"
#include "type_gml.CPolarCSPropertyType.h"
#include "type_gml.CPolarCSType.h"
#include "type_gml.CPolygonPatchArrayPropertyType.h"
#include "type_gml.CPolygonPatchType.h"
#include "type_gml.CPolygonType.h"
#include "type_gml.CPolyhedralSurfaceType.h"
#include "type_gml.CPrimeMeridianPropertyType.h"
#include "type_gml.CPrimeMeridianType.h"
#include "type_gml.CPriorityLocationPropertyType.h"
#include "type_gml.CProcedurePropertyType.h"
#include "type_gml.CProjectedCRSPropertyType.h"
#include "type_gml.CProjectedCRSType.h"
#include "type_gml.CQNameList.h"
#include "type_gml.CQuantityExtentType.h"
#include "type_gml.CQuantityPropertyType.h"
#include "type_gml.CRangeParametersType.h"
#include "type_gml.CRangeSetType.h"
#include "type_gml.CRectangleType.h"
#include "type_gml.CRectifiedGridCoverageType.h"
#include "type_gml.CRectifiedGridDomainType.h"
#include "type_gml.CRectifiedGridType.h"
#include "type_gml.CReferenceType.h"
#include "type_gml.CRelatedTimeType.h"
#include "type_gml.CResultType.h"
#include "type_gml.CRingPropertyType.h"
#include "type_gml.CRingType.h"
#include "type_gml.CScaleType.h"
#include "type_gml.CSequenceRuleEnumeration.h"
#include "type_gml.CSequenceRuleType.h"
#include "type_gml.CShellPropertyType.h"
#include "type_gml.CShellType.h"
#include "type_gml.CSignType.h"
#include "type_gml.CSingleCRSPropertyType.h"
#include "type_gml.CSingleOperationPropertyType.h"
#include "type_gml.CSolidArrayPropertyType.h"
#include "type_gml.CSolidPropertyType.h"
#include "type_gml.CSolidType.h"
#include "type_gml.CSpeedType.h"
#include "type_gml.CSphereType.h"
#include "type_gml.CSphericalCSPropertyType.h"
#include "type_gml.CSphericalCSType.h"
#include "type_gml.CStringOrRefType.h"
#include "type_gml.CSuccessionType.h"
#include "type_gml.CSurfaceArrayPropertyType.h"
#include "type_gml.CSurfaceInterpolationType.h"
#include "type_gml.CSurfacePatchArrayPropertyType.h"
#include "type_gml.CSurfacePropertyType.h"
#include "type_gml.CSurfaceType.h"
#include "type_gml.CTargetPropertyType.h"
#include "type_gml.CTemporalCRSPropertyType.h"
#include "type_gml.CTemporalCRSType.h"
#include "type_gml.CTemporalCSPropertyType.h"
#include "type_gml.CTemporalCSType.h"
#include "type_gml.CTemporalDatumBaseType.h"
#include "type_gml.CTemporalDatumPropertyType.h"
#include "type_gml.CTemporalDatumType.h"
#include "type_gml.CTimeCSPropertyType.h"
#include "type_gml.CTimeCSType.h"
#include "type_gml.CTimeCalendarEraPropertyType.h"
#include "type_gml.CTimeCalendarEraType.h"
#include "type_gml.CTimeCalendarPropertyType.h"
#include "type_gml.CTimeCalendarType.h"
#include "type_gml.CTimeClockPropertyType.h"
#include "type_gml.CTimeClockType.h"
#include "type_gml.CTimeCoordinateSystemType.h"
#include "type_gml.CTimeEdgePropertyType.h"
#include "type_gml.CTimeEdgeType.h"
#include "type_gml.CTimeIndeterminateValueType.h"
#include "type_gml.CTimeInstantPropertyType.h"
#include "type_gml.CTimeInstantType.h"
#include "type_gml.CTimeIntervalLengthType.h"
#include "type_gml.CTimeNodePropertyType.h"
#include "type_gml.CTimeNodeType.h"
#include "type_gml.CTimeOrdinalEraPropertyType.h"
#include "type_gml.CTimeOrdinalEraType.h"
#include "type_gml.CTimeOrdinalReferenceSystemType.h"
#include "type_gml.CTimePeriodPropertyType.h"
#include "type_gml.CTimePeriodType.h"
#include "type_gml.CTimePositionType.h"
#include "type_gml.CTimePositionUnion.h"
#include "type_gml.CTimePrimitivePropertyType.h"
#include "type_gml.CTimeReferenceSystemType.h"
#include "type_gml.CTimeTopologyComplexPropertyType.h"
#include "type_gml.CTimeTopologyComplexType.h"
#include "type_gml.CTimeTopologyPrimitivePropertyType.h"
#include "type_gml.CTimeType.h"
#include "type_gml.CTimeUnitType.h"
#include "type_gml.CTinType.h"
#include "type_gml.CTopoComplexMemberType.h"
#include "type_gml.CTopoComplexType.h"
#include "type_gml.CTopoCurvePropertyType.h"
#include "type_gml.CTopoCurveType.h"
#include "type_gml.CTopoPointPropertyType.h"
#include "type_gml.CTopoPointType.h"
#include "type_gml.CTopoPrimitiveArrayAssociationType.h"
#include "type_gml.CTopoPrimitiveMemberType.h"
#include "type_gml.CTopoSolidType.h"
#include "type_gml.CTopoSurfacePropertyType.h"
#include "type_gml.CTopoSurfaceType.h"
#include "type_gml.CTopoVolumePropertyType.h"
#include "type_gml.CTopoVolumeType.h"
#include "type_gml.CTransformationPropertyType.h"
#include "type_gml.CTransformationType.h"
#include "type_gml.CTrianglePatchArrayPropertyType.h"
#include "type_gml.CTriangleType.h"
#include "type_gml.CTriangulatedSurfaceType.h"
#include "type_gml.CUnitDefinitionType.h"
#include "type_gml.CUnitOfMeasureType.h"
#include "type_gml.CUomIdentifier.h"
#include "type_gml.CUomSymbol.h"
#include "type_gml.CUomURI.h"
#include "type_gml.CUserDefinedCSPropertyType.h"
#include "type_gml.CUserDefinedCSType.h"
#include "type_gml.CValueArrayPropertyType.h"
#include "type_gml.CValueArrayType.h"
#include "type_gml.CValuePropertyType.h"
#include "type_gml.CVectorType.h"
#include "type_gml.CVerticalCRSPropertyType.h"
#include "type_gml.CVerticalCRSType.h"
#include "type_gml.CVerticalCSPropertyType.h"
#include "type_gml.CVerticalCSType.h"
#include "type_gml.CVerticalDatumPropertyType.h"
#include "type_gml.CVerticalDatumType.h"
#include "type_gml.CVolumeType.h"
#include "type_gml.CbooleanList.h"
#include "type_gml.CbooleanOrNilReason.h"
#include "type_gml.CbooleanOrNilReasonList.h"
#include "type_gml.CdoubleList.h"
#include "type_gml.CdoubleOrNilReason.h"
#include "type_gml.CdoubleOrNilReasonList.h"
#include "type_gml.CintegerList.h"
#include "type_gml.CintegerOrNilReason.h"
#include "type_gml.CintegerOrNilReasonList.h"
#include "type_gml.CstringOrNilReason.h"
#include "type_gml.CbooleanOrNilReasonListType.h"
#include "type_gml.CCountExtentTypeType.h"
#include "type_gml.CintegerOrNilReasonListType.h"
#include "type_gml.CNilReasonTypeType.h"
#include "type_gml.CDecimalMinutesTypeType.h"
#include "type_gml.CdoubleOrNilReasonListType.h"
#include "type_gml.CintegerListType.h"
#include "type_gml.CArcMinutesTypeType.h"
#include "type_gml.CArcSecondsTypeType.h"
#include "type_gml.CrowsType.h"
#include "type_gml.CRowType.h"
#include "type_gml.CNameOrNilReasonType.h"
#include "type_gml.CNameOrNilReasonType2.h"
#include "type_gml.CNameOrNilReasonListType.h"
#include "type_gml.CrefLocationType.h"
#include "type_gml.CNameListType.h"
#include "type_gml.CintegerOrNilReasonType.h"
#include "type_gml.CintegerOrNilReasonType2.h"
#include "type_gml.CDegreeValueTypeType.h"
#include "type_gml.CdirectionType.h"
#include "type_gml.CdoubleListType.h"
#include "type_gml.CCompassPointEnumerationType.h"
#include "type_gml.CFileValueModelTypeType.h"
#include "type_gml.CNCNameListType.h"
#include "type_gml.CdoubleOrNilReasonType.h"
#include "type_gml.CdoubleOrNilReasonType2.h"
#include "type_gml.CNilReasonEnumerationType.h"
#include "type_gml.CNilReasonEnumerationType2.h"
#include "type_gml.CNilReasonTypeType2.h"
#include "type_gml.CNilReasonTypeType3.h"
#include "type_gml.CrelativePositionType.h"
#include "type_gml.CSequenceRuleEnumerationType.h"
#include "type_gml.CCalDateType.h"
#include "type_gml.CTimePositionUnionType.h"
#include "type_gml.CTimeUnitTypeType.h"
#include "type_gml.CTimeUnitTypeType2.h"
#include "type_gml.CcontrolPointType.h"
#include "type_gml.CbooleanOrNilReasonType.h"
#include "type_gml.CbooleanOrNilReasonType2.h"
#include "type_gml.CstringOrNilReasonType.h"
#include "type_gml.CstringOrNilReasonType2.h"

// namespace "http://www.w3.org/1999/xlink"

// namespace "http://www.w3.org/2001/XMLSchema"
#include "type_xs.CENTITIES.h"
#include "type_xs.CENTITY.h"
#include "type_xs.CID.h"
#include "type_xs.CIDREF.h"
#include "type_xs.CIDREFS.h"
#include "type_xs.CNCName.h"
#include "type_xs.CNMTOKEN.h"
#include "type_xs.CNMTOKENS.h"
#include "type_xs.CNOTATION.h"
#include "type_xs.CName.h"
#include "type_xs.CQName.h"
#include "type_xs.CanySimpleType.h"
#include "type_xs.CanyType.h"
#include "type_xs.CanyURI.h"
#include "type_xs.Cbase64Binary.h"
#include "type_xs.Cboolean.h"
#include "type_xs.Cbyte.h"
#include "type_xs.Cdate.h"
#include "type_xs.CdateTime.h"
#include "type_xs.Cdecimal.h"
#include "type_xs.Cdouble.h"
#include "type_xs.Cduration.h"
#include "type_xs.Cfloat.h"
#include "type_xs.CgDay.h"
#include "type_xs.CgMonth.h"
#include "type_xs.CgMonthDay.h"
#include "type_xs.CgYear.h"
#include "type_xs.CgYearMonth.h"
#include "type_xs.ChexBinary.h"
#include "type_xs.Cint.h"
#include "type_xs.Cinteger.h"
#include "type_xs.Clanguage.h"
#include "type_xs.Clong.h"
#include "type_xs.CnegativeInteger.h"
#include "type_xs.CnonNegativeInteger.h"
#include "type_xs.CnonPositiveInteger.h"
#include "type_xs.CnormalizedString.h"
#include "type_xs.CpositiveInteger.h"
#include "type_xs.Cshort.h"
#include "type_xs.Cstring.h"
#include "type_xs.Ctime.h"
#include "type_xs.Ctoken.h"
#include "type_xs.CunsignedByte.h"
#include "type_xs.CunsignedInt.h"
#include "type_xs.CunsignedLong.h"
#include "type_xs.CunsignedShort.h"
#include "type_xs.CbooleanType.h"
#include "type_xs.CstringType.h"
#include "type_xs.CdateTimeType.h"
#include "type_xs.CdecimalType.h"
#include "type_xs.CintegerType.h"
#include "type_xs.CdoubleType.h"
#include "type_xs.CanyURIType.h"
#include "type_xs.CdurationType.h"
#include "type_xs.CpositiveIntegerType.h"
#include "type_xs.CnonNegativeIntegerType.h"
#include "type_xs.CdateType.h"
#include "type_xs.CtimeType.h"

// finished

#endif //_INCLUDED_gie_H_
