////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by XMLSpy 2011 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


#ifndef gie_STDAFX_H_INCLUDED
#define gie_STDAFX_H_INCLUDED

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#if _MSC_VER < 1300
#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information
#endif

#if !defined( __GNUC__ )

#include <tchar.h>
#include <windows.h>

#endif


#include <xercesc/dom/DOM.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>


#ifdef _DEBUG
	#pragma comment(lib, "xerces-c_3D")
#else
	#pragma comment(lib, "xerces-c_3")
#endif



#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information



#include <iostream>
#include <string>


#include "Altova/Altova.h"
#include "Altova/SchemaTypes.h"
#include "Altova/AltovaException.h"

#include "AltovaXML/XmlException.h"
#include "AltovaXML/Node.h"
using namespace altova;


//{{AFX_INSERT_LOCATION}}

#endif // gie_STDAFX_H_INCLUDED
